/**
 * @file esta_mfcrids.hpp
 * @brief ESTA ManufacturerIDs
 * @details Auto generated from https://tsp.esta.org/tsp/working_groups/CP/mfctrIDs.php
 * @date 2025-03-16T01:01:29Z
 */

#ifndef ESTA_MFCTRIDS_HPP
#define ESTA_MFCTRIDS_HPP

#include <map>
#include <string>

namespace ESTA {

	/**
	 * @details The Manufacturer ID Database is a public listing of 
	 * (1) all the two-byte IDs assigned per clauses E4 and D5.12 of ANSI E1.11, Entertainment Technology - 
	 * USITT DMX512-A - Asynchronous Serial Data Transmission Standard for Controlling Lighting Equipment and Accessories,
	 * and (2) all the Textual Organization Identifiers assigned per clause 3.2 of ACN EPI 16.
	 */
	namespace ManufacturerIDs {
		/**
		 * @name Prototype Range
		 * @details
		 * Manufacturer IDs 7FF0h through 7FFFh are reserved for prototyping and experimental use
		 * by a manufacturer while that manufacturer is waiting for an assigned Manufacturer ID.
		 * They are not permitted to be used in product that is shipping.
		 *@{*/
		const uint16_t PROTOTYPE_BEGIN = 0x7FF0; /**< Prototyping range begin */
		const uint16_t PROTOTYPE_END = 0x7FFF; /**< Prototyping range end */
		/**@}*/

		using namespace std::string_literals;
		/**
		 * @brief Manufacturer Company names
		 * @details Indexed by Manufacturer ID
		 */
		const std::map<uint16_t, std::wstring> Manufacturers = {
			{0x0000, L"ESTA"s},
			{0x0000, L"PLASA"s},
			{0x0001, L"GEE"s},
			{0x0002, L"Abstract AVR Ltd."s},
			{0x0003, L"Chromatech Lighting Co., Ltd."s},
			{0x0008, L"Guangdong Nanguang Photo & Video Systems Co., Ltd."s},
			{0x0009, L"Aputure Imaging Industries Co., Ltd."s},
			{0x000A, L"Interactive Imagination Ltd."s},
			{0x000B, L"Phospec Industries Inc."s},
			{0x000C, L"WAC Lighting Co."s},
			{0x000D, L"Guangzhou Haoteng Lighting Co., Ltd."s},
			{0x000E, L"Yaoxing Lighting Equipment  (Guanghzou）Co., Ltd."s},
			{0x000F, L"Shenzhen L-Thinker Technology Co., Ltd."s},
			{0x0010, L"Dongguan Mi Xing Electronic Technology Co., Ltd."s},
			{0x0011, L"Beijing Kedeshengye Technology Service Co., Ltd."s},
			{0x0012, L"Apex Pro Light Co., Ltd."s},
			{0x0013, L"Litemover BV"s},
			{0x0014, L"SIRS Electronics, Inc."s},
			{0x0015, L"Lumencraft Lighting Solutions"s},
			{0x0016, L"Shenzhen Xuntek Electronics Co., Ltd"s},
			{0x0017, L"Ereimul"s},
			{0x0018, L"Macroblock, Inc."s},
			{0x0019, L"Odelic Co., Ltd."s},
			{0x001A, L"DLL Ltd."s},
			{0x001B, L"Changsha Sunrise Electronic Technology Co. Ltd."s},
			{0x001C, L"Kindwin Technology (HK) Ltd."s},
			{0x001D, L"Luminator Technology Group"s},
			{0x001E, L"Shenzhen Lumi Lime Technology Limited"s},
			{0x0020, L"Wattle IT"s},
			{0x0021, L"Electric Foundry Ltd."s},
			{0x0022, L"PixelFLEX, LLC"s},
			{0x0057, L"Blackbezt Lighting Technology Co., Ltd."s},
			{0x0058, L"Big Dipper Laser Science and Technology Co.,Ltd."s},
			{0x0059, L"Laysion Lighting Technology Co., Ltd."s},
			{0x005A, L"TPD Lighting"s},
			{0x006A, L"AIMTECH Electronik Tasarim Ltd. Sti."s},
			{0x006B, L"SALZBRENNER media GmbH"s},
			{0x006C, L"Flash-Butrym Sp.J."s},
			{0x006D, L"AA Tasarim Ltd."s},
			{0x006E, L"WHITEvoid GmbH"s},
			{0x006F, L"AC Power Distribution/ACT Lighting Inc."s},
			{0x0070, L"Instalighting GmbH"s},
			{0x0071, L"Guangzhou Huaxinyuan Electronics Co., Ltd."s},
			{0x0072, L"Guangzhou Zenith Aurora Lighting Co., Ltd."s},
			{0x0073, L"Meijay Technologies Co., Ltd."s},
			{0x0074, L"Thomann GmbH"s},
			{0x0075, L"ODELI"s},
			{0x0076, L"R. S. Schwarze Elektrotechnik Moderne Industrieelektronik GmbH"s},
			{0x0077, L"CHAMP Licht"s},
			{0x0078, L"Andy Lighting Technology Group Ltd."s},
			{0x0079, L"Leyard Opto Electronics Co., Ltd."s},
			{0x007A, L"Equivalent"s},
			{0x007B, L"alurays lighting technology GmbH"s},
			{0x007C, L"Huizhou Desay Intelligent Technology Co., Ltd."s},
			{0x007D, L"JMS Pro Light"s},
			{0x007E, L"Stichting Hypar Collective"s},
			{0x0080, L"Shenzhen AOTO Electronics Co., Ltd."s},
			{0x0081, L"Pino Solutions"s},
			{0x0082, L"LKE Lasershowtechnik GmbH"s},
			{0x0083, L"Guangzhou Bright Moon Technology Co., Ltd."s},
			{0x0084, L"LEDIXIS (Exalux brand)"s},
			{0x0085, L"Guangzhou Nanshi Light Equipment Co., Ltd."s},
			{0x0086, L"Intella System Co., Ltd."s},
			{0x0087, L"LMBD"s},
			{0x0088, L"Guangzhou YaFeng Optoelectronic Equipment Co., Ltd."s},
			{0x0089, L"Vulcan Lighting"s},
			{0x008A, L"Guangzhou Lees Electronics Co., Ltd."s},
			{0x008B, L"Opto Tech Corporation"s},
			{0x008C, L"LRX Lighting (Dwight Crane Ltd.)"s},
			{0x008D, L"Guangzhou Minghao Electronic Technology Co., Ltd."s},
			{0x008E, L"Guangzhou Ao Mei Di Stage Lighting Equipment Co.,Ltd."s},
			{0x008F, L"Jiangmen Coolfish Technology Co., Ltd."s},
			{0x0090, L"Cyclops Lighting"s},
			{0x0091, L"Guangzhou Shuozhi Optoelectronic Technology Co., Ltd. (Konelite)"s},
			{0x0092, L"digiLED (UK) Ltd."s},
			{0x0093, L"Luminous Show Technology Ltd."s},
			{0x0094, L"Joinmax Display Technology Co., Ltd."s},
			{0x0095, L"Ningbo Jeg Lighting Tech Co., Ltd."s},
			{0x0096, L"SiChuan YuZhiWei Information Technology Lt., Co."s},
			{0x0097, L"AdvancedRay (Beijing) Science & Technology Industries Co., Ltd."s},
			{0x0098, L"Dedo Weigert Film GmbH"s},
			{0x009A, L"Golden Sea Disco Light Manufacturer"s},
			{0x009B, L"Guangzhou Jiawei Electronic Technology Co., Ltd."s},
			{0x009C, L"LuxBalance Lighting"s},
			{0x009E, L"Guangzhou Flying Butterfly Stage Lighting Equipment Co., Ltd."s},
			{0x009F, L"Enedo Power SpA"s},
			{0x00A0, L"Shenzhen Dicolor Optoelectronics Co., Ltd."s},
			{0x00A1, L"Creative Lighting And Sound Systems Pty Ltd."s},
			{0x00A2, L"EMP Designs Ltd."s},
			{0x00A3, L"GuangZhou Huanshi Lighting Equipment Co., Limited"s},
			{0x00A4, L"SAKMA Electronica Industrial S.A.U."s},
			{0x00A5, L"Delta Electronics, Inc."s},
			{0x00A6, L"Sensation Lighting Technology Co., Ltd."s},
			{0x00A7, L"Syncronorm GmbH"s},
			{0x00A8, L"Iwasaki Electric Co., Ltd."s},
			{0x00A9, L"Richter Lighting Technologies GmbH"s},
			{0x00AA, L"Hangzhou Easun Technology Co., Ltd."s},
			{0x00AB, L"MFX Asia Co., Ltd"s},
			{0x00AC, L"ZhouChuang Industrial Co. Limited"s},
			{0x00AD, L"ColorDeve Co. Limited"s},
			{0x00AE, L"Vitrulux Ltd"s},
			{0x00AF, L"NanoPLC LLC"s},
			{0x00B0, L"ARENA LUCI s.r.l."s},
			{0x00B1, L"Guangzhou Omarte Lighting Co., Ltd."s},
			{0x00B2, L"unonovesette srl"s},
			{0x00B3, L"LANTERN"s},
			{0x00B4, L"Lumos Design"s},
			{0x00B5, L"Suga koubou Co., Ltd."s},
			{0x00B6, L"DiGidot Technologies BV"s},
			{0x00B7, L"Bron Elektronik AG"s},
			{0x00B8, L"Shenzhen Singba Light Technology Co., Ltd."s},
			{0x00B9, L"Guangzhou Baiyun District Sanjie Eletronic Stage Lighting Audio Equipment Factory"s},
			{0x00BA, L"LiteGear Inc."s},
			{0x00BB, L"Digital Lighting Engineering & Design, LLC"s},
			{0x00BC, L"Ambion GmbH (Ambrain)"s},
			{0x00BD, L"numeo GmbH"s},
			{0x00BE, L"The Light Luminary for Cine and TV S.L. (VELVET LIGHT)"s},
			{0x00BF, L"LumiOS (GTR Industries)"s},
			{0x00C0, L"Foshan Yinhe Lanjing Lighting & Electrical Co., Ltd."s},
			{0x00C1, L"Jingchuang Water Technology"s},
			{0x00C2, L"Ledogen"s},
			{0x00C3, L"Xicato"s},
			{0x00C4, L"Guangzhou Dahe Electronic Technology Co. Ltd."s},
			{0x00C5, L"DAGE Stage Lighting Master Co., Ltd."s},
			{0x00C6, L"Guangzhou Lantian Electronic Technology Co., Ltd."s},
			{0x00C7, L"THOR"s},
			{0x00C8, L"Constell8 NV"s},
			{0x00C9, L"Pangaea Technology"s},
			{0x0101, L"St. Anne Engineering GmbH"s},
			{0x0102, L"Bortis Elektronik"s},
			{0x0103, L"Fontana Technologies"s},
			{0x0104, L"Blizzard Lighting, LLC"s},
			{0x0105, L"LIGHTHOW (SHANGHAI) Ltd."s},
			{0x0106, L"A.L.A. Equipment Company Ltd."s},
			{0x0107, L"Inventronics (Hangzhou), Inc."s},
			{0x0108, L"Haya Lighting Equipment Limited"s},
			{0x0109, L"V-Productions"s},
			{0x010A, L"Elektralite"s},
			{0x010B, L"DesignLED Technology (HK) Co., Ltd."s},
			{0x010C, L"SES (Entertainment Services) Ltd."s},
			{0x010D, L"Lumos / DMLite"s},
			{0x010E, L"Guangzhou ATON Lighting Technology Co.,Ltd"s},
			{0x010F, L"Saco Technologies Inc."s},
			{0x0110, L"APF S.r.l."s},
			{0x0111, L"Radig Hard & Software"s},
			{0x0112, L"RGB Lighting Equipment  Co., Ltd."s},
			{0x0113, L"Airstar SAS"s},
			{0x0114, L"BSL Lighting"s},
			{0x0115, L"Kontrolcla Show Control S.L."s},
			{0x0116, L"SmoothLUX B.V."s},
			{0x0117, L"AD Toyo Lighting (Guangzhou) Co.,Ltd"s},
			{0x0118, L"Vello Light Co., Ltd."s},
			{0x0119, L"Peter Schneyder Design Management GmbH"s},
			{0x011A, L"Guangzhou Hotion Technology Co., Ltd."s},
			{0x011B, L"Jumptronic GmbH"s},
			{0x011C, L"Letong Electronic (Guangzhou) Co., Ltd."s},
			{0x011D, L"Yangzhou Zhituo Lighting Vision Technology Co., Ltd."s},
			{0x011E, L"Master LED"s},
			{0x011F, L"STF s.r.l."s},
			{0x0144, L"KW-Veranstaltungstechnik"s},
			{0x016C, L"LGR"s},
			{0x016D, L"Hive Lighting"s},
			{0x016E, L"Artled Technology Corp."s},
			{0x016F, L"SQD  Lighting Co. Ltd"s},
			{0x018F, L"Guangzhou YiCheng Light Industry Ltd."s},
			{0x0190, L"Wizlogics Co., Ltd."s},
			{0x0191, L"Sycra Technologies"s},
			{0x0192, L"Metro Marine LLC"s},
			{0x0193, L"DMF Lighting"s},
			{0x0199, L"Ocean LED Marine Ltd."s},
			{0x019A, L"TwoGain Electronics"s},
			{0x019B, L"ElectroTAS Soluciones Profesionales"s},
			{0x019C, L"Ningbo Snappy Optoelectronics Co., Ltd."s},
			{0x019F, L"DaisaLed Ltd."s},
			{0x01A0, L"Light With LED"s},
			{0x01A1, L"Yuesheng Stage Light Limited"s},
			{0x01A2, L"Art Lighting Production, s.r.o."s},
			{0x01A3, L"Dongguan Yongya Technology Co., Ltd"s},
			{0x01A4, L"Custom Effects LED Solutions Inc."s},
			{0x01A5, L"MJ Lighting Co., Ltd."s},
			{0x01A6, L"Hengmei Lighting Technology Co., Ltd."s},
			{0x01A8, L"ZongDa Photoelectricity Science and Technology Co., Ltd."s},
			{0x01A9, L"Shenzhen Uniview LED Ltd. Co."s},
			{0x01AA, L"Videndum Production Solutions Inc."s},
			{0x01AB, L"Shanghai Euchips Industrial Co., Ltd."s},
			{0x01AC, L"DongGuan  Phcistar Optoelectronics Technology Co., Ltd."s},
			{0x01AF, L"Hunan Minghe Opto Tech Co., Ltd."s},
			{0x01B1, L"Lightcare A/S"s},
			{0x01B2, L"DJSI Schinstad ANS (Northern Light)"s},
			{0x01B3, L"Ricardo Dias"s},
			{0x01B4, L"Inventeq B.V."s},
			{0x01B5, L"Beijing Soft Rock Technology Development Co., Ltd."s},
			{0x01BE, L"BEN-RI Electronica S.A."s},
			{0x01C7, L"SCHIEDERWERK GmbH"s},
			{0x01C8, L"Guangzhou JINLIN Stage Lighting Equipment Co., Ltd."s},
			{0x01C9, L"ALPHA LITE Inc."s},
			{0x01CA, L"CASCADE s.a.s."s},
			{0x01CB, L"ILT Italy SRL"s},
			{0x01CC, L"Portman Custom Lights"s},
			{0x01CD, L"Compulite Systems (2000) LTD"s},
			{0x01CE, L"Railiks Enterprises"s},
			{0x01CF, L"SRM Technik GmbH"s},
			{0x01D0, L"Shanghai Semping Electronics Co., Ltd."s},
			{0x01D1, L"Yarilo Pro"s},
			{0x01D2, L"GIP Innovation Tools GmbH"s},
			{0x01D3, L"JSC Aksera"s},
			{0x01D4, L"x-labs"s},
			{0x01D5, L"Shenzhen Liantronics Co., Ltd"s},
			{0x01D6, L"Argent Data Systems, Inc."s},
			{0x01D7, L"LIMEDIA"s},
			{0x01D8, L"Daniel Large Lighting"s},
			{0x01D9, L"Lightronics Inc."s},
			{0x01DA, L"Guangzhou Daisy Electronic Technology Co., Ltd."s},
			{0x01DB, L"Logen Ltd."s},
			{0x01DC, L"LED Linear GmbH"s},
			{0x01DD, L"Photonia srl"s},
			{0x01DE, L"Guangzhou Baiyun Xinxiang Lighting Equipment Factory (XPRO LIGHT)"s},
			{0x01DF, L"GuangZhou Dream Lighting Equipment Co., Ltd."s},
			{0x01E0, L"IBN Labs Ltd."s},
			{0x0200, L"Lighting Infusion LLC"s},
			{0x0201, L"Blinkinlabs, LLC"s},
			{0x0202, L"Paul Heuts"s},
			{0x0203, L"Artemide S.p.A"s},
			{0x0204, L"LIGHTLINE Lasertechnik GmbH"s},
			{0x0205, L"SmartShow UK"s},
			{0x0206, L"Studio Due Light S.r.l."s},
			{0x0207, L"SILL LIGHTS GmbH"s},
			{0x0208, L"Shenzhen Yuming Vision Technology Co., Ltd."s},
			{0x0209, L"ER Productions"s},
			{0x020A, L"Seebacher GmbH"s},
			{0x0210, L"Leksa Lighting Technologies Pvt. Ltd."s},
			{0x0211, L"Arkaos S.A."s},
			{0x0212, L"Frame The Space (FTSLED)"s},
			{0x0213, L"Huizhou visionX Technology Co., Ltd."s},
			{0x0214, L"Impactrum"s},
			{0x021A, L"WizzuLED by Scooon"s},
			{0x0223, L"ShenZhen Focus Vision Intelligent System Co., Ltd."s},
			{0x0224, L"Vanguard LED Displays"s},
			{0x0225, L"Northern Lights Electronic Design, LLC"s},
			{0x0235, L"Company 235, LLC"s},
			{0x0242, L"ABLELITE INTERNATIONAL"s},
			{0x024C, L"FBFX Ltd"s},
			{0x025B, L"Imlight-Showtechnic"s},
			{0x026F, L"Acuity Brands Lighting Inc."s},
			{0x0280, L"Arrigo Lighting"s},
			{0x0286, L"RMLX"s},
			{0x028F, L"GRE Alpha Electronics Ltd."s},
			{0x02A0, L"LLC Likhoslavl Plant of Lighting Engineering (Svetotehnika)"s},
			{0x02A1, L"LLC Moscow Experimental Lighting Plant (TeleMechanic)"s},
			{0x02A2, L"OJSC Kadoshkinsky electrotechnical"s},
			{0x02A3, L"Big Bang Lightning"s},
			{0x02A4, L"McNicoll Entertainment Systems"s},
			{0x02AA, L"Jinnax Opto Technology Co., Ltd."s},
			{0x02AB, L"Rift Labs"s},
			{0x02AC, L"PSL Electronik Sanayi ve Ticaret A.S."s},
			{0x02AD, L"SAVI Controls LLC"s},
			{0x02AE, L"Tea Engineering Ltd."s},
			{0x02AF, L"JMAZ Group, Inc."s},
			{0x02B0, L"DMXControl-Projects e.V."s},
			{0x02B1, L"Global Design Solutions Korea"s},
			{0x02B2, L"Guangzhou Harbinger Co., Ltd."s},
			{0x02BA, L"Chainzone Technology (Foshan) Co., Ltd."s},
			{0x02BC, L"PXP Technology"s},
			{0x02BD, L"RE-Engineering"s},
			{0x02C8, L"Growflux LLC"s},
			{0x02C9, L"Theatrixx Technologies"s},
			{0x02CA, L"Acclaim Lighting"s},
			{0x02CB, L"GVA Lighting, Inc."s},
			{0x02CC, L"Brightix"s},
			{0x02D0, L"Winona Lighting"s},
			{0x02D1, L"Hoffmeister Leuchten GmbH"s},
			{0x02E1, L"Tait Towers Manufacturing Inc."s},
			{0x02E2, L"CLF Lighting BV."s},
			{0x02EA, L"d3 Technologies Ltd."s},
			{0x02EB, L"Amolvin Research & Development Lab."s},
			{0x02EC, L"Lutron Electronics"s},
			{0x02ED, L"OpenLX SP Ltd."s},
			{0x02EE, L"Firma GUTKOWSKI - Gutkowski Jan"s},
			{0x02EF, L"ABLETECH Co., Ltd."s},
			{0x02F0, L"iColor LED Shenzhen Co., Ltd."s},
			{0x02F1, L"Lichtmanufaktur Berlin GmbH"s},
			{0x02FE, L"L8 LLC"s},
			{0x02FF, L"Guangzhou Eway Stage Equipment Technology Co., Ltd."s},
			{0x0302, L"Swefog Technology Group AB"s},
			{0x0303, L"Shanghai Moons' Automation Control Co., Ltd"s},
			{0x0305, L"DiCon Fiberoptics, Inc."s},
			{0x0306, L"feno GmbH"s},
			{0x0307, L"Ledium Kft."s},
			{0x0308, L"ImageCue LLC"s},
			{0x030A, L"Shenzhen Colordreamer Tech Ltd."s},
			{0x030B, L"Guangzhou Wanrui Stage Light Equipment Co., Ltd."s},
			{0x030F, L"EK INC (formerly Guangzhou Litewise Lighting Equipments Co., Ltd.)"s},
			{0x0311, L"Guangzhou PUGUANG Electronic Technology Co., Ltd."s},
			{0x0312, L"Guangzhou Xingkong Studio Lighting Co., Ltd."s},
			{0x032C, L"Carallon Ltd."s},
			{0x033A, L"Lux Lumen"s},
			{0x034B, L"Rosstech Signals Inc."s},
			{0x0378, L"KASUGA"s},
			{0x038F, L"Strich Labs"s},
			{0x0391, L"Alcorn McBride Inc."s},
			{0x0393, L"i2Systems"s},
			{0x0394, L"Prism Projection"s},
			{0x039B, L"Lightforce Lasertechnik"s},
			{0x03A1, L"INAREX INC."s},
			{0x03A2, L"licht.team"s},
			{0x03A8, L"ARTFOX"s},
			{0x03AA, L"AIGA Electronic (GuangZhou) Co., Ltd."s},
			{0x03AB, L"ABMICROLONDON"s},
			{0x03C6, L"NYSOFT"s},
			{0x03CE, L"MVI LLC"s},
			{0x03D5, L"eX Systems"s},
			{0x03D6, L"i-Lumen"s},
			{0x03DA, L"QST LED"s},
			{0x03E8, L"Acson"s},
			{0x03F0, L"jpbaye.de"s},
			{0x03FA, L"ART-DMX"s},
			{0x0402, L"Exato"s},
			{0x0404, L"Luminxa"s},
			{0x040E, L"Optoma Corporation"s},
			{0x0411, L"SoundSwitch"s},
			{0x0412, L"D's DMX"s},
			{0x041C, L"IMLIGHT"s},
			{0x0424, L"FLUX ECLAIRAGE"s},
			{0x0428, L"ITSTECH"s},
			{0x0430, L"BOE MLED Technology Co., Ltd"s},
			{0x043C, L"Volux Lighting"s},
			{0x0440, L"Guangzhou VAS Lighting Co., Ltd."s},
			{0x044E, L"Ben Peoples Industries, LLC"s},
			{0x044F, L"B2 Co., Ltd."s},
			{0x0455, L"Lamp & Pencil"s},
			{0x047C, L"LedsGo"s},
			{0x0480, L"ASUSTeK Computer Inc."s},
			{0x0486, L"LANZ (CZ) Lighting Ltd"s},
			{0x048E, L"Krisledz Pte. Ltd."s},
			{0x048F, L"Grand Canyon LED Lighting System (Suzhou) Co., Ltd."s},
			{0x04A6, L"MEB Veranstaltungstechnik GmbH"s},
			{0x04A9, L"Edward J. Keefe Jr."s},
			{0x04B2, L"Shenzhen Meiyad Optoelectronics Co., Ltd"s},
			{0x04B4, L"SKT Inc."s},
			{0x04B5, L"Major"s},
			{0x04B6, L"IntiLED"s},
			{0x04B8, L"Guangzhou Hongcai Stage Equipment Co., Ltd."s},
			{0x04C4, L"Ephesus Lighting, Inc."s},
			{0x04CA, L"RT-DMX"s},
			{0x04CC, L"Yubang Ruiying (Zhongshan) Electronics Co., LTD"s},
			{0x04CE, L"Quisda"s},
			{0x04D6, L"Kessil"s},
			{0x04D7, L"Targetti Sankey Spa"s},
			{0x04D8, L"Guangzhou Hong Yuan Electronic Technology Co., LTD."s},
			{0x04DC, L"Modern Stage Service Projects"s},
			{0x04DD, L"Topstriving Photoelectricity Technology Co., Ltd."s},
			{0x04E6, L"Kelvix"s},
			{0x04EE, L"Tivoli Lighting"s},
			{0x04F0, L"SIGMA NET"s},
			{0x04F4, L"Zeraus"s},
			{0x04FC, L"Syncrolite LLC"s},
			{0x0504, L"MYHP Limited"s},
			{0x050A, L"ChamSys Ltd."s},
			{0x051C, L"Ambitsel, Inc."s},
			{0x0520, L"ANLC Ltd"s},
			{0x0529, L"OSRAM"s},
			{0x052A, L"DELTACAST"s},
			{0x0536, L"tarm AG"s},
			{0x0537, L"TERMINAL-COM"s},
			{0x0540, L"EverBrighten Co., Ltd."s},
			{0x0550, L"Pyrotechnics Management, Inc. (PMI)"s},
			{0x0555, L"Maresch Electronics"s},
			{0x0556, L"RAYSYS"s},
			{0x055F, L"PRO-SOLUTIONS"s},
			{0x0560, L"VingtQuatreVolts"s},
			{0x056B, L"COSMOLIGHT SRL"s},
			{0x056C, L"Lumascape Lighting Industries"s},
			{0x0573, L"JIAXING XINHUALI LIGHTING & SOUNDING CO., LTD."s},
			{0x057A, L"RVE S.A.S."s},
			{0x0580, L"Innovation LED  Limited"s},
			{0x0582, L"Jack LINE"s},
			{0x0586, L"K 5600, Inc."s},
			{0x0588, L"GuangZhou XiangMing Light Limited"s},
			{0x0592, L"MIRAGE B.V."s},
			{0x0596, L"ReveLux"s},
			{0x05A0, L"Stage Smarts AB"s},
			{0x05A4, L"IMMOLAS"s},
			{0x05A8, L"Owl Labs"s},
			{0x05AB, L"Shenzhen Lesan Lighting Co., Ltd."s},
			{0x05AC, L"PRstage"s},
			{0x05B5, L"Turkowski GmbH"s},
			{0x05BC, L"CantoUSA"s},
			{0x05C0, L"Vertigo"s},
			{0x05CF, L"Brighten Technology Development Co., Ltd."s},
			{0x05D3, L"D-LED Illumination Technologies Ltd."s},
			{0x05DA, L"Spacyal"s},
			{0x05E0, L"esp_dmx"s},
			{0x05E2, L"KORRO PLUS"s},
			{0x05E8, L"Snap One"s},
			{0x05EB, L"GUANGZHOU BO WEI TE LIGHTING  CO.LTD"s},
			{0x05EF, L"Guangzhou Chai Yi Light Co., Ltd."s},
			{0x05F2, L"O'Light"s},
			{0x05F6, L"Otiru Oy"s},
			{0x05F7, L"Immersive Design Studios Inc."s},
			{0x0600, L"TELMIC Neo"s},
			{0x0602, L"Guangzhou Jinhong Stage Lighting Equipment.Co.,ltd"s},
			{0x0606, L"Guangzhou YiGuang Stage Lighting Co., Ltd."s},
			{0x0609, L"Diginet Control Systems Pty Ltd"s},
			{0x060A, L"Kindwin Opto Electronic (ShenZhen) Co. Ltd"s},
			{0x060B, L"Lighting Science Group (formerly LED Effects, Inc.)"s},
			{0x060D, L"HANIL TNC  CO.,LTD"s},
			{0x061C, L"LEDRAYS INC"s},
			{0x0622, L"Lupo SRL"s},
			{0x0623, L"JAS LIGHTING & SOUND CO., LTD."s},
			{0x0624, L"S4 Lights"s},
			{0x0628, L"ERP Power"s},
			{0x062A, L"LEDstructures"s},
			{0x062B, L"CKC Lighting Co., Ltd."s},
			{0x063A, L"AVM Belgium BVBA"s},
			{0x063C, L"LaserNet"s},
			{0x0644, L"COLEDER DISPLAY CO., LTD."s},
			{0x0645, L"MATSUMURA ELECTRIC MFG. CO. , LTD."s},
			{0x064D, L"KXD LIGHTING CO., LIMITED"s},
			{0x064E, L"My Method"s},
			{0x0650, L"RDC, Inc. d.b.a. LynTec"s},
			{0x0653, L"USAI, LLC"s},
			{0x0654, L"HUNAN XIANG CAIXU FILM AND TELEVISION CULTURE CO.LTD"s},
			{0x0658, L"AZCOLOR LITE CO., LIMITED"s},
			{0x065E, L"OFilms"s},
			{0x0660, L"QSTECH CO.,LTD"s},
			{0x0668, L"Motion FX"s},
			{0x066B, L"AVANT-GARDE DE STUDIO FZ LLC"s},
			{0x066F, L"GUANGZHOU CY LIGHTING EQUIPMENT CO.,LTD"s},
			{0x0674, L"Raylogic Control systems Pvt Ltd."s},
			{0x067A, L"Inster Co, Ltd"s},
			{0x067C, L"LOTRONIC SA"s},
			{0x0682, L"Beijing Ming Rui Lighting Technology Co., Ltd."s},
			{0x0684, L"LEDART LLC"s},
			{0x0685, L"IBL/ESD-Datentechnik GmbH"s},
			{0x0687, L"INSMARINE LLC"s},
			{0x0688, L"LUCIDISCENA"s},
			{0x0689, L"GUANGDONG DONE POWER TECHNOLOGY CO"s},
			{0x068C, L"Hitmusic SAS"s},
			{0x068E, L"GUANGZHOU TEANMA STAGE LIGHTING FACTORY"s},
			{0x068F, L"LEDEC GROUP LIMITED"s},
			{0x0692, L"TORO SYSTEM"s},
			{0x0696, L"SHENZHEN HOION LIGHTING CO.,LTD"s},
			{0x0697, L"Shenzhen LED Innovator Technology Co., Ltd"s},
			{0x0698, L"Techni-Lux"s},
			{0x06A0, L"Light.Audio.Design"s},
			{0x06A1, L"ProTec GmbH"s},
			{0x06A3, L"RODLIGHT ALBRECHT SILBERBERGER"s},
			{0x06AC, L"GOLVER PROJECTS S.L."s},
			{0x06AD, L"LEDMAN OPTOELECTRONIC CO.,LTD."s},
			{0x06AE, L"CANARA LIGHTING INDUSTRIES PVT LTD"s},
			{0x06AF, L"ZHEJIANG JINGRI TECHNOLOGY CO.,LTD"s},
			{0x06B3, L"NANOLUMENS, INC."s},
			{0x06B6, L"GUANGDONG VSHINE LIGHTING TECHNOLOGY CO.,LTD"s},
			{0x06B9, L"GUANGZHOU DASEN LIGHTING CORPORATION LIMITED"s},
			{0x06BB, L"IQ COMPANY Ltd."s},
			{0x06C4, L"RHENAC Systems GmbH"s},
			{0x06C5, L"ZHIYUN INFORMATION (INTERNATIONAL) TECHNOLOGY CO., LIMITED"s},
			{0x06C7, L"L&L Luce&Light"s},
			{0x06C8, L"Dongguan Huiguan Culture Technology Co., Ltd."s},
			{0x06CA, L"Leding"s},
			{0x06CE, L"American-Pro International"s},
			{0x06D1, L"BIRUN ELECTRONIC INDUSTRIAL CO., LTD"s},
			{0x06D2, L"LIGHTSTAR (BEIJING) ELECTRONIC CORPORATION"s},
			{0x06D3, L"Boerner Distribution International GmbH"s},
			{0x06D9, L"ELECTROCONCEPT SARL"s},
			{0x06DD, L"GRUPPO SIGI SRLS"s},
			{0x06E0, L"SHENZHEN LONGRUN OPTOELECTRONIC CO., LTD"s},
			{0x06E1, L"Burck IT GmbH & Co. KG"s},
			{0x06E2, L"ScreenCo"s},
			{0x06E4, L"Dydell B.V."s},
			{0x06E6, L"Equipson S.A."s},
			{0x06EC, L"SISTEMA Jsc"s},
			{0x06F0, L"CTG sp. z o.o."s},
			{0x06F1, L"Aqualux Lighting"s},
			{0x06F8, L"CHONGQING XINYUANHUI OPTOELECTRONIC TECHNOLOGY CO.,LTD"s},
			{0x0700, L"OXYGEN SMD Ltd"s},
			{0x0702, L"Drinelec"s},
			{0x0706, L"LINEAR TECHNOLOGIE"s},
			{0x0707, L"Conceptinetics Technologies and Consultancy Ltd."s},
			{0x0708, L"AK-LIGHT"s},
			{0x070C, L"Pixout SIA"s},
			{0x070D, L"Lumenwerx ULC"s},
			{0x070E, L"PragmaLab"s},
			{0x070F, L"Theatrelight New Zealand"s},
			{0x0710, L"D.T.S. Illuminazione srl"s},
			{0x0711, L"Halonix Technologies Pvt Ltd."s},
			{0x0712, L"Laser Imagineering GmbH"s},
			{0x0716, L"Artem Ltd."s},
			{0x0718, L"Eagle Lite"s},
			{0x071A, L"YHX Visual"s},
			{0x071F, L"Moss LED Inc"s},
			{0x0724, L"PHC Lighting & BMS Sp. z o.o."s},
			{0x072B, L"NEWSUBSTANCE Ltd."s},
			{0x072C, L"SGM A/S"s},
			{0x072D, L"Sting Alleman"s},
			{0x072F, L"RayComposer - R. Adams"s},
			{0x0732, L"Galaxia Electronics"s},
			{0x0734, L"CPOINT"s},
			{0x073A, L"AML Lighting Co.,LTD"s},
			{0x073B, L"Corsair Technology Ltd."s},
			{0x0740, L"Arkalumen"s},
			{0x0744, L"DMX Pro Sales, LLC"s},
			{0x0745, L"Guangzhou Wingo Stage Light Co., Ltd"s},
			{0x0748, L"Chromateq"s},
			{0x074F, L"Panasonic Corporation"s},
			{0x0753, L"F&V Europe B.V."s},
			{0x0758, L"IMPOLUX GmbH"s},
			{0x075F, L"LEDEngin Inc."s},
			{0x0766, L"MR-Space LLC"s},
			{0x076A, L"BeamZ  (Tronios B.V.)"s},
			{0x076E, L"DecoLed, LLC"s},
			{0x0776, L"lumenetix"s},
			{0x077B, L"GENLED Brands"s},
			{0x0782, L"R9 Lighting"s},
			{0x0786, L"DMXDesktop"s},
			{0x078A, L"FATEC sarl"s},
			{0x078E, L"SHENZHEN BGLOPTO TECHNOLOGY Co., LTD."s},
			{0x0792, L"MY-Semi Inc."s},
			{0x0797, L"ARCPROLED Limited"s},
			{0x079B, L"Pro Church Lights"s},
			{0x079F, L"VPS Group, LLC"s},
			{0x07A3, L"Guangzhou GBR PROLIGHT GROUP CO.,LTD (GBR PROLIGHT)"s},
			{0x07A5, L"X LED Systems"s},
			{0x07AD, L"CLS LED BV"s},
			{0x07AE, L"A-LITE B.V."s},
			{0x07B0, L"ADDiCTiON BoX GbR"s},
			{0x07B1, L"TBF-PyroTec GmbH"s},
			{0x07B3, L"Shenzhen Fabulux Technology Co., Ltd"s},
			{0x07B5, L"ARM Automation, Inc"s},
			{0x07B6, L"Minleon USA"s},
			{0x07B8, L"Zhuhai Demi Technology Co., Ltd."s},
			{0x07BA, L"Tradia Co., LTD"s},
			{0x07BB, L"Shenzhen SOSEN Electronics Co., Ltd."s},
			{0x07BE, L"Sanko Device Co.Ltd."s},
			{0x07C0, L"Code Mercenaries GmbH"s},
			{0x07C2, L"BOOQlight BV"s},
			{0x07C5, L"SBS Lighting LLC"s},
			{0x07C6, L"BK Lighting"s},
			{0x07C8, L"Sidus Link Ltd."s},
			{0x07CC, L"Griven S.r.l."s},
			{0x07CF, L"MH-Sound"s},
			{0x07D1, L"Made By Mouse LTD"s},
			{0x07D2, L"Guangdong The One Studio Co., Limited"s},
			{0x07D5, L"PHIDA Stage Equipment Co., Ltd"s},
			{0x07D6, L"Lite Puter Enterprise Co., Ltd."s},
			{0x07DA, L"Flytech s.r.l."s},
			{0x07DC, L"EVLight (Guangzhou) Co.,Ltd."s},
			{0x07E8, L"ROCKETSIGN Technology HK Ltd"s},
			{0x07E9, L"TechLink Co., Ltd."s},
			{0x07EA, L"Le Maitre Ltd"s},
			{0x07EF, L"Guangzhou V-Show Pro Lighting Co., Ltd."s},
			{0x07F0, L"Lifud Technology Co., Ltd"s},
			{0x07F2, L"CB Electronics"s},
			{0x07F3, L"Sam Light"s},
			{0x07F4, L"LED Flex Ltd."s},
			{0x07F5, L"Shenzhen ATENTI Technologies Co., Ltd"s},
			{0x07F6, L"Electric Distribution Systems"s},
			{0x07F7, L"Dakco Technologies Co., Ltd."s},
			{0x07F8, L"Ultimate Technology Solutions GmbH"s},
			{0x07F9, L"Bion Technologies GmbH"s},
			{0x07FA, L"Shenzhen Pony Systems Tech Co., Ltd."s},
			{0x07FC, L"Electro Mind Co., Ltd."s},
			{0x07FD, L"THELIGHT Luminary for Cine and TV S.L."s},
			{0x07FE, L"Shenzhen Apexls Optoelectronic Co., Ltd."s},
			{0x07FF, L"Guangzhou HOMEI LIGHT Manufacturer"s},
			{0x0800, L"Hongyeah Light"s},
			{0x0801, L"Guangzhou Favolite Stage Lighting Co., Ltd."s},
			{0x0802, L"AstralPool"s},
			{0x0803, L"Guangzhou FutureColor Electronic Technology Co., Ltd."s},
			{0x0804, L"K&G Visual Technology"s},
			{0x0805, L"T.C.M. Light-Solutions"s},
			{0x0806, L"Air Giants Limited"s},
			{0x0807, L"Event Lighting Pty, Ltd."s},
			{0x0808, L"Cooper Lighting - Zero 88"s},
			{0x0809, L"mumoco GmbH"s},
			{0x080A, L"Shenzhen FantaLED Electronics Co., Ltd"s},
			{0x080D, L"HBJ Elektronik"s},
			{0x080F, L"NavoLabs"s},
			{0x0810, L"BDS Studios"s},
			{0x0811, L"V-PRO"s},
			{0x0812, L"Yamagiwa Corporation"s},
			{0x0813, L"Shenzhen Scenico Optoelectronic Co., Ltd."s},
			{0x0814, L"squareV"s},
			{0x0816, L"Benjamin Graf Ton- und Medientechnik"s},
			{0x081C, L"MR Electronics Ltd."s},
			{0x081E, L"LOBO Electronic GmbH"s},
			{0x0822, L"Hangzhou YD Illumination Co., Ltd"s},
			{0x0823, L"Opito Labs GmbH"s},
			{0x0824, L"Almotechnos CO.,LTD."s},
			{0x0827, L"PIXREAL"s},
			{0x0829, L"CR-TEC Photoelectric"s},
			{0x082E, L"QubiCast GmbH"s},
			{0x0832, L"Shenzhen EXC-LED Technology Co.,Ltd"s},
			{0x0836, L"Nyvoll Lys"s},
			{0x0838, L"LaserAV"s},
			{0x083A, L"Bright Ideas Custom Electronics Inc."s},
			{0x083C, L"TDT Productions"s},
			{0x083E, L"Guangdong Hua Chen Film & Television Stage Project Co., Ltd."s},
			{0x083F, L"Shenzhen LeiFei Lighting Technologies Co.,Ltd."s},
			{0x0840, L"Shenzhen Zwich Science and Technology Co.Ltd."s},
			{0x0841, L"Guangzhou ICON Lighting Co.,Ltd"s},
			{0x0843, L"BHL Lichttechniek"s},
			{0x0845, L"Cush Light LLC"s},
			{0x0846, L"LDR - Luci della Ribalta Srl"s},
			{0x0848, L"SLC - Static Light Company Ltd"s},
			{0x084B, L"Neon Circus Ltd"s},
			{0x084C, L"Guangzhou Ba Lin Electronic Technology Co., Ltd."s},
			{0x084D, L"Guangzhou NECO Stage Lighting Factory"s},
			{0x084E, L"RGBshine Technology Co. Ltd."s},
			{0x084F, L"Mantic Lighting Co.,Ltd"s},
			{0x0850, L"Proland Group, LLC"s},
			{0x0851, L"Junction Inc. Ltd"s},
			{0x0853, L"Royal Ballet and Opera"s},
			{0x0854, L"NEC Display Solutions, Ltd."s},
			{0x0854, L"Sharp NEC Display Solutions, Ltd."s},
			{0x0855, L"GODOX Photo Equipment Co., Ltd."s},
			{0x0856, L"Ctrl Element ehf"s},
			{0x0858, L"Juno Lighting Group"s},
			{0x085A, L"Guangzhou Ming Jing Stage Light Equipment Co., Ltd."s},
			{0x085B, L"Tolifo (Dongguan) Photographic Equipment Co. Ltd"s},
			{0x085E, L"MMS Distribution Ltd"s},
			{0x085F, L"Media Visions, Inc."s},
			{0x0862, L"illuminous"s},
			{0x0863, L"XTEC Industries Pte Ltd"s},
			{0x0864, L"Hangzhou Youte Power., Co. Ltd"s},
			{0x0865, L"Contrade GmbH"s},
			{0x0866, L"PAL Lighting"s},
			{0x0867, L"Huizhou LATU Film Equipment Co., Ltd"s},
			{0x0868, L"Ushio America, Inc."s},
			{0x0869, L"Club Cannon LLC"s},
			{0x086A, L"Shenzhen Chip Optech Co.,LTD"s},
			{0x086C, L"Bafa Elektronik ve Işık Tasarımları Sanayii Ticaret LTD Sti."s},
			{0x086D, L"Velaflame, LLC"s},
			{0x086E, L"Guangzhou Hi-LTTE Electronics Technology Co.,Ltd"s},
			{0x086F, L"MARTINI RUS LLC"s},
			{0x0870, L"Hunan YESTECH Optoelectronic Co., Ltd"s},
			{0x0871, L"Changsha Maya Special Effects Equipment Co., Ltd"s},
			{0x0872, L"GigaTera Lighting Inc."s},
			{0x0873, L"Guangzhou BKLite Stage Lighting Equipment Co.,LTD"s},
			{0x0874, L"Snow Professional Lighting"s},
			{0x0875, L"ARC Solid-State Lighting Corp."s},
			{0x0876, L"Power Gems LTD"s},
			{0x0877, L"Skaff New Zealand Ltd"s},
			{0x0878, L"OTTEC Technology GmbH"s},
			{0x087A, L"Dextra Group Plc"s},
			{0x087B, L"About Time Technologies"s},
			{0x087C, L"Telectran International Pty Ltd."s},
			{0x087D, L"TPV Technology Group"s},
			{0x0880, L"GuangZhou LiDang Technology Inc."s},
			{0x0881, L"Shenzhen Genesis-Systech Co., Ltd."s},
			{0x0883, L"CEE Lighting Equipment Co.Ltd"s},
			{0x0884, L"Bright Group"s},
			{0x0885, L"SIRS-E"s},
			{0x0886, L"KLIK Systems"s},
			{0x0887, L"PrimOtek s.r.l.s."s},
			{0x0888, L"Banglux Lighting Technology Co., Ltd."s},
			{0x0889, L"Guangzhou Shenghui Electronic Technology Co., Ltd"s},
			{0x088A, L"Highendled Electronics Company Limited"s},
			{0x088B, L"Shenzhen Doit Vision Co., Ltd"s},
			{0x088C, L"Guangzhou Yi Sheng Yuan Electronic Co.,Ltd(Esun)"s},
			{0x088D, L"Guangzhou Ling Yang  lighting Science and Technology Co.,Ltd"s},
			{0x088E, L"Stage One International Co., Ltd."s},
			{0x088F, L"First Design System Inc."s},
			{0x0890, L"Taurus Light Co.,Limited"s},
			{0x0891, L"Feiner Lichttechnik GMBH"s},
			{0x0892, L"DongGuan Ruishen Technology Co.,Ltd"s},
			{0x0893, L"Brighten LED Lighting Limited"s},
			{0x0894, L"Dongguan HCP Technology Co., Ltd."s},
			{0x0895, L"Dolby Laboratories, Inc."s},
			{0x0896, L"CSD Design and Fabrication"s},
			{0x0899, L"Shenzhen Huimont Technology Co., Ltd"s},
			{0x089A, L"ADL Electronics Ltd."s},
			{0x089D, L"gobo.ws"s},
			{0x089E, L"Cronic Lighting"s},
			{0x08A1, L"Shenzhen Gloshine Technology Co., Ltd"s},
			{0x08A2, L"Guangzhou Gesida Light Equipment Co., Ltd."s},
			{0x08A3, L"Redot Visual Effect Technologies (Shenzhen) Co., Ltd"s},
			{0x08A4, L"Adam Hall GmbH"s},
			{0x08A5, L"White Wing Logic"s},
			{0x08A6, L"impulswerk.de"s},
			{0x08A7, L"GuangZhou Deliya Opto-electronic Tech Co., Ltd"s},
			{0x08A8, L"Guangzhou Yunpeng Lighting Equipment Co. Ltd."s},
			{0x08A9, L"Lighten Corp."s},
			{0x08AA, L"PiXL Factory"s},
			{0x08AB, L"Qdot Lighting Limited"s},
			{0x08AC, L"Bushveld Labs"s},
			{0x08AD, L"Optical Productions LLC"s},
			{0x08AE, L"Technical Audio Group Pty Ltd"s},
			{0x08AF, L"AAdyn Technology"s},
			{0x08B0, L"KIM Lighting"s},
			{0x08B1, L"Fujian Starnet Evideo Information System Co.,Ltd."s},
			{0x08B2, L"MCI Group"s},
			{0x08B3, L"Stealth Light srl"s},
			{0x08B4, L"Ledera Technology Co.,Ltd"s},
			{0x08B5, L"ShenZhen Sunny Xiao Technology Co., Ltd."s},
			{0x08B6, L"Graf Lichttechnik UG"s},
			{0x08B8, L"LEDScape Lighting"s},
			{0x08B9, L"Guangzhou Hua Rong Electronic Technology Co., Ltd."s},
			{0x08BA, L"Meteor Lighting"s},
			{0x08BB, L"Guangzhou CHEN Electronic Technology Co., Ltd."s},
			{0x08BC, L"Michael Parkin"s},
			{0x08BD, L"Lug Light Factory Sp. z o. o."s},
			{0x08BE, L"Shenzhen FloatStone Technology Co., Ltd."s},
			{0x08BF, L"Times Square Stage Lighting Inc."s},
			{0x08C0, L"Real Tech International LTD."s},
			{0x08C1, L"Project SSSHH Incorporated"s},
			{0x08C2, L"Guangzhou Huipu Stage Effect Equipment Co., Ltd"s},
			{0x08C3, L"Guangzhou Spark Stage Equipment Co. Ltd"s},
			{0x08C4, L"Jacek Wagner"s},
			{0x08C5, L"EHRGEIZ Lichttechnik GmbH"s},
			{0x08C6, L"Guangzhou Ever Famous Electronic Co.,Ltd"s},
			{0x08C7, L"Shenzhen SOSTRON Technology Co., Ltd"s},
			{0x08C9, L"LEDitgo Videowall Germany GmbH"s},
			{0x08CA, L"Foshan City Xuandao Optoelectronics Equipment Co., Ltd"s},
			{0x08CB, L"Practical LEDs.com"s},
			{0x08CC, L"Guangzhou Santu Stage Lighting Equipment Co.Ltd"s},
			{0x08CE, L"Zhejiang DGX Electronic Technology Co.,Ltd"s},
			{0x08D0, L"Image Engineering"s},
			{0x08D1, L"Shenzhen Leqi Network Technology Co., Ltd."s},
			{0x08D3, L"SVI Public Company Limited"s},
			{0x08D4, L"Sensa-Lite Ltd."s},
			{0x08D5, L"Sense Effects"s},
			{0x08D6, L"Guangzhou Precision Vision Intelligent Equipment Co, Ltd"s},
			{0x08D7, L"PatternAgents, LLC"s},
			{0x08D8, L"W.A. Benjamin Electric Co."s},
			{0x08D9, L"STILED"s},
			{0x08DA, L"PLC Intelligent Technology (Shanghai) Co., Ltd."s},
			{0x08DD, L"Matthew Tong"s},
			{0x08DE, L"Delta Electronics (Jiangsu) Ltd."s},
			{0x08DF, L"DetaiLED Solutions"s},
			{0x08E0, L"Red Arrow Controls"s},
			{0x08E1, L"Shenzhen CLT Electronics Co.,LTD"s},
			{0x08E2, L"Particle Studio Ltd."s},
			{0x08E3, L"Guangzhou JinZhiHui Electronic Technology Co.,Ltd."s},
			{0x08E4, L"LMP Lichttechnik Vertriebsgesellschaft GmbH & Co KG"s},
			{0x08E6, L"Shenzhen VisionMax Technology Co., Ltd"s},
			{0x08E7, L"3A Guangzhou Electronics Co., Ltd"s},
			{0x08E8, L"North Engineering"s},
			{0x08EA, L"Changchun Cedar Electronic Technology Co.,Ltd."s},
			{0x08EB, L"Guangzhou Lixin Lighting Co., Ltd."s},
			{0x08EC, L"Marvin Nadrowski"s},
			{0x08ED, L"ShowLED"s},
			{0x08EE, L"Spacelights"s},
			{0x08EF, L"Guangzhou RuiYang lighting technology co. LTD."s},
			{0x08F0, L"Guang Dong LMJ Lighting Co., Ltd"s},
			{0x08F1, L"SanDevices, LLC"s},
			{0x08F2, L"Virtualny Agronom Ltd."s},
			{0x08F3, L"Outdoor Lasers Ltd."s},
			{0x08F4, L"MC Electronic Technology(GZ) Co., Ltd."s},
			{0x08F5, L"Fufeng lighting"s},
			{0x08F6, L"Eulum Design, LLC"s},
			{0x08F7, L"Neotek Lighting"s},
			{0x08F8, L"Liberal Logic Inc."s},
			{0x08F9, L"ACS - Ackerman Computer Sciences"s},
			{0x08FA, L"Phaton Lighting Co., Ltd."s},
			{0x08FB, L"RPA Electronic Solutions Inc."s},
			{0x08FC, L"Lights By Brian"s},
			{0x08FD, L"Koto Electric Co., Ltd."s},
			{0x08FE, L"Zhuhai Shengchang Electronics Co., Ltd."s},
			{0x0900, L"nox multimedia GmbH"s},
			{0x0901, L"GermTec GmbH & Co. KG"s},
			{0x0902, L"DongGuan Betterway Lighting Co.,Ltd"s},
			{0x0903, L"Shenzhen INFiLED Electronics, Ltd."s},
			{0x0904, L"Bigbear Co., Ltd."s},
			{0x0905, L"Locimation Pty Ltd"s},
			{0x0906, L"Crystal Technica Limited"s},
			{0x0907, L"Shenzhen GCL Electronics Co., Ltd"s},
			{0x0908, L"Guangzhou DeLong Stage Equipment Co., Ltd."s},
			{0x0909, L"Beijing Starlight Electronics Co., Ltd."s},
			{0x090A, L"Jiangmen Seekway Technology Limited"s},
			{0x090B, L"StarLighting"s},
			{0x090C, L"GRE Alpha"s},
			{0x090E, L"Sichuan esRadio Technology Co., Ltd"s},
			{0x090F, L"Shenzhen Dingli Display Technology Co., Ltd"s},
			{0x0910, L"Shenzhen Tecnon EXCO-Vision Technology Co., Ltd."s},
			{0x0911, L"Guangzhou Aceda Professional  Lighting  Co., Ltd."s},
			{0x0912, L"ags - Wissenschaftliche Arbeitsgemeinschaft fur Studio- und Senderfragen"s},
			{0x0913, L"Guangzhou ECK Light Equipment Company Limited"s},
			{0x0914, L"Xenio"s},
			{0x0915, L"Guangzhou Chuangfeng Photoelectric Equipment Co., Ltd."s},
			{0x0916, L"ACTOR-MATE CO., LTD."s},
			{0x0917, L"Gavtronics"s},
			{0x0918, L"David O Smith Design"s},
			{0x0919, L"Foshan Leiyuan Photoelectric Co., LTD"s},
			{0x091A, L"Celex LED Technology Ltd."s},
			{0x091B, L"Krislite Pte. Ltd."s},
			{0x091D, L"TouchPlate Technologies Inc."s},
			{0x091E, L"Vanilla Internet Ltd"s},
			{0x091F, L"Yaham Recience Technology Co,. ltd."s},
			{0x0920, L"Vexica Technology Limited"s},
			{0x0921, L"Guangzhou mengyi stage lighting equipment co., LTD."s},
			{0x0922, L"von Gaisberg Engineering"s},
			{0x0923, L"Hangzhou Roleds Lighting System Co., Ltd."s},
			{0x0925, L"Guangzhou Aiweidy Lighting Acoustics Equipment Co.,Ltd."s},
			{0x0926, L"Elumeros Lighting Limited"s},
			{0x0927, L"Guangzhou Mingying Electronic Technology Co., Ltd."s},
			{0x0928, L"Chaostreff Backnang e.V."s},
			{0x0929, L"UPlight stage equipment(GZ) CO., Ltd."s},
			{0x092A, L"Unitech Digital Media srl"s},
			{0x092B, L"Guangzhou Lightful Stage Lighting&Sound Equipment Co,.Ltd."s},
			{0x092C, L"Guangzhou Chaoran Computer Co., Ltd."s},
			{0x092D, L"LG Electronics"s},
			{0x092E, L"YouEasy (Dongguan) Electronics Technology Co.,Ltd"s},
			{0x092F, L"Guangzhou Shinelight Stage Equipment Factory"s},
			{0x0930, L"jiaozuo shengguang film &equipment Co. Ltd"s},
			{0x0931, L"Cristal Controles"s},
			{0x0932, L"GUANGZHOU BORAY ELECTRON CO.,LTD"s},
			{0x0933, L"Beyond Lighting WLL"s},
			{0x0934, L"Zenopix Electronic Limited Company"s},
			{0x0935, L"Guangzhou Huadu District Richa Lighting Equipment Factory"s},
			{0x0936, L"AquaTronic"s},
			{0x0937, L"Huizhou Zhonghan Electronic Technology Co., Ltd"s},
			{0x0938, L"Guangzhou Vanray Lighting Equipment CO.,Ltd."s},
			{0x0939, L"Edelmann Electronics"s},
			{0x093A, L"HDT impex s.r.o."s},
			{0x093B, L"Guangzhou Hongmingwei Stage Lighting Co., Ltd."s},
			{0x093D, L"Sichuan Hushan Electric Co. Ltd"s},
			{0x093F, L"Guangzhou Julong Platform Lighting Equipment Factory"s},
			{0x0940, L"Shenzhen CreateLED Electronics Co., Ltd"s},
			{0x0941, L"Shenzen Zhuoyang Intelligent Technology Co., Ltd."s},
			{0x0942, L"Showjockey Technology Co., Ltd"s},
			{0x0943, L"Guangzhou Guangying Optoelectronics Co., Ltd"s},
			{0x0945, L"Guangzhou Lin Xiang Stage Lighting Equipment CO.,LTD"s},
			{0x0946, L"TBE Srl"s},
			{0x0947, L"Shenzhen MOSO Electronics Technology Co., Ltd"s},
			{0x0948, L"Wisconsin Lighting Lab, Inc. (WiLL)"s},
			{0x0949, L"Shenzhen Jiuzhou Optoelectronic Technology"s},
			{0x094A, L"Funovation, Inc"s},
			{0x094B, L"Invisua Lighting BV"s},
			{0x094C, L"Shenzhen Xiezhen Electronics Co., Ltd."s},
			{0x094D, L"Quantum Theory"s},
			{0x094E, L"Myostat Motion Control"s},
			{0x0951, L"Guangzhou GTD Lighting Technology Co., Ltd"s},
			{0x0952, L"Guangzhou Sunway Entertainment Equipment Co., Ltd."s},
			{0x0953, L"Boumakers Techniek"s},
			{0x0954, L"Ledtop Visual Ltd."s},
			{0x0955, L"8lightspace limited"s},
			{0x0956, L"Expromo Europe A/S"s},
			{0x0957, L"White Light Ltd"s},
			{0x0958, L"Illum Technology LLC (previously Verde Designs, Inc.)"s},
			{0x0959, L"Urbs Lighting, LLC"s},
			{0x095A, L"kLabs Research UK"s},
			{0x095B, L"Wuhan Zhongtian Jiaye Mechanical and Electrical Engineering Co. LTD"s},
			{0x095C, L"Thomas Neumann Licht und Tontechnik"s},
			{0x095D, L"Silver Curve Ltd"s},
			{0x095E, L"Hondel Lighting Limited"s},
			{0x095F, L"Elaborated Networks GmbH"s},
			{0x0960, L"Fineline Solutions Ltd."s},
			{0x0962, L"Finland Lighting Oy"s},
			{0x0963, L"Foshan Sololighting Technology Co., Ltd"s},
			{0x0964, L"Inventions Guité Inc."s},
			{0x0965, L"Fontana Fountains"s},
			{0x0967, L"Arcus Licht- und Praesentationstechnik GmbH"s},
			{0x0968, L"Guangzhou Beyond Lighting Co., Limited."s},
			{0x0969, L"VCS Vision Control Solutions GmbH"s},
			{0x096C, L"Guangzhou Nebula Stage Lighting Equipment Co., Ltd"s},
			{0x096D, L"Guangzhou Xin Yilong Stage Lighting Equipment Co., Limited"s},
			{0x096E, L"Calvitia Limited"s},
			{0x096F, L"Shenzhen showho technolgy co.,ltd"s},
			{0x0970, L"Aurum Engineering GmbH"s},
			{0x0971, L"Plura Europe GmbH"s},
			{0x0972, L"Holochrom GmbH"s},
			{0x0973, L"Guangzhou Eagle Wei Photoelectric Technology Co., Ltd."s},
			{0x0974, L"Marumo Electric Co., Ltd."s},
			{0x0975, L"KB Design"s},
			{0x0976, L"Axion Lighting LLC"s},
			{0x0977, L"Guangzhou HuaYong Intelligent Technology Co., Ltd."s},
			{0x0978, L"LE Veranstaltungstechnik"s},
			{0x097A, L"Teamboyce Limited"s},
			{0x097D, L"Brink Electronics"s},
			{0x097E, L"Guangzhou Deyi Lighting Co., Ltd."s},
			{0x097F, L"RaumZeitLabor e.V."s},
			{0x0980, L"Moog Animatics"s},
			{0x0981, L"Luxam, Ltd."s},
			{0x0982, L"AC Entertainment Products Ltd."s},
			{0x0983, L"S Squared Innovations Inc."s},
			{0x0984, L"Laserworld AG"s},
			{0x0986, L"ROE Visual Co. Ltd."s},
			{0x0987, L"mathertel.de"s},
			{0x0989, L"YeGrin Liteworks"s},
			{0x098A, L"DongGuan JuYang Electric Co., Ltd"s},
			{0x098B, L"Glow Motion Technologies, LLC."s},
			{0x098C, L"Shenzhen Longrich Energy Sources Technology Co., Ltd."s},
			{0x098D, L"Batmink Ltd."s},
			{0x098E, L"Ecosense Lighting Inc"s},
			{0x098F, L"Digital Sputnik Lighting"s},
			{0x0990, L"Stagelight Holding"s},
			{0x0991, L"Guangdong Pomelo Photoelectric Equipment Co., Ltd"s},
			{0x0992, L"Guangzhou Fengyi Stage Lighting Equipment Co., Ltd."s},
			{0x0993, L"Shenzhen Trigger digital Technology Co., LTD"s},
			{0x0995, L"Rasha Professional"s},
			{0x0996, L"CCI Power Supplies, LLC"s},
			{0x0997, L"Star Iluminacao Computadorizada LTDA"s},
			{0x0999, L"Concept Smoke Systems Ltd."s},
			{0x099A, L"Aixz International (S)"s},
			{0x099B, L"Luminoscape Lighting Limited"s},
			{0x099D, L"Frenexport SPA"s},
			{0x099E, L"LLC Lighting Technologies production"s},
			{0x09A0, L"Rnet Lighting Technology Limited"s},
			{0x09A1, L"Veranstaltungstechnik König"s},
			{0x09A2, L"Fountain People"s},
			{0x09A3, L"Shenzhen Lightlink Display Technology Co., Ltd"s},
			{0x09A4, L"Brighter Lighting Sp. z.o.o."s},
			{0x09A5, L"Prolight Concepts Ltd."s},
			{0x09AA, L"Rushstage Show Lighting Limited"s},
			{0x09AD, L"Dongguan Ensure Electronic Technology Co., LTD"s},
			{0x09AE, L"Robert Juliat"s},
			{0x09AF, L"Autotech Co."s},
			{0x09B0, L"Luminii"s},
			{0x09B1, L"Shenzhen Lianxinke Microelectronics Co., Ltd"s},
			{0x09B2, L"Guangzhou Hedong Electronics Co., LTD"s},
			{0x09B3, L"Aquatique Show Int."s},
			{0x09B4, L"Brompton Technology Ltd."s},
			{0x09B5, L"XBlack Visual Products"s},
			{0x09B6, L"Second String Studios"s},
			{0x09B7, L"inCon-trol water systems"s},
			{0x09B8, L"Prolites S.A.L."s},
			{0x09BA, L"Supervoimed OU"s},
			{0x09BB, L"Guangzhou Yiyi Technology Co., Ltd."s},
			{0x09BD, L"Shenzhen Zhongbo Photoelectric Co., Ltd"s},
			{0x09BE, L"Arctos Showlasertechnik GmbH"s},
			{0x09C0, L"Guangzhou Rainbow Lighting Equipment CO.,LTD"s},
			{0x09C1, L"Argetron Elektrik Elektronik Organizasyon Gida San. ve Dis Tic. Ltd. Sti."s},
			{0x09C3, L"Velleman nv"s},
			{0x09C4, L"Guangzhou XinHuang Industrial Co., Ltd."s},
			{0x09C6, L"Photon Manufacturing"s},
			{0x09C7, L"ShoCobra"s},
			{0x09C8, L"Crystal Fountains Inc."s},
			{0x09CC, L"Motomuto Aps"s},
			{0x09D0, L"Luminar Enterprises"s},
			{0x09D1, L"Environmental Lights"s},
			{0x09D2, L"Shenzhen Siwelo Technology Co., LTD"s},
			{0x09D3, L"WLPS Wodielite Production Services"s},
			{0x09D4, L"Guangzhou Yilaiming Photoelectric Technology Co., Ltd"s},
			{0x09D5, L"Shenzhen ImagineVision Technology Limited"s},
			{0x09D6, L"Mittomakers"s},
			{0x09D7, L"Unilumin Group"s},
			{0x09D8, L"Pioneer Lighting Solutions India Pvt Ltd"s},
			{0x09DC, L"Froggys Fog"s},
			{0x09DD, L"Planet Innovation Products Inc"s},
			{0x09DE, L"Matthias Bauch Software"s},
			{0x09E9, L"Starway"s},
			{0x09EE, L"Suzhou Pinzong Electronic Technology, CO.,Ltd"s},
			{0x09EF, L"Andrea Croce"s},
			{0x09F8, L"UberDisplays"s},
			{0x09FC, L"deskontrol electronics"s},
			{0x0A01, L"Star-Reach Corporation"s},
			{0x0AAA, L"AAA-LUX"s},
			{0x0D0C, L"SmartDC Inc."s},
			{0x0D0E, L"DMX Engineering LLC"s},
			{0x1112, L"Zhuhai Bincolor Electronic Technology Co., Ltd."s},
			{0x1113, L"SiliconCore Technology, Inc."s},
			{0x1200, L"Seekway Technology Limited"s},
			{0x1201, L"PRICOM Design"s},
			{0x1202, L"Ushio Lighting, Inc."s},
			{0x1203, L"Movecat GmbH"s},
			{0x1204, L"ARES s.r.l. - Socio Unico"s},
			{0x1205, L"Carbon Lighting Limited"s},
			{0x1206, L"Hangel Technology Co., Ltd."s},
			{0x1207, L"BSK Networks GbR"s},
			{0x1208, L"Nuvolight GmbH & Co KG"s},
			{0x1209, L"Philippe Bergeron Lights"s},
			{0x120A, L"Bulldog Lighting and Events, Inc."s},
			{0x120B, L"Brilliant Stages Ltd."s},
			{0x120C, L"Shanxi Tian Gong Sheng Optoelectronic Equipment Technology Co."s},
			{0x1211, L"Recrealab"s},
			{0x1212, L"HPL Light Company"s},
			{0x1221, L"SAGITTER-SDJ-Proel"s},
			{0x1222, L"SM International"s},
			{0x1234, L"ESTA"s},
			{0x12DA, L"Newlab S.r.l."s},
			{0x12E0, L"Luxlight Skandinavien AB"s},
			{0x12EA, L"Kolberg Percussion GmbH"s},
			{0x12F4, L"Stage Services Ltd."s},
			{0x12FA, L"Hollywood Rentals LLC"s},
			{0x12FE, L"City Design S.p.A."s},
			{0x131E, L"Blossom Communications Corp."s},
			{0x1337, L"Raven Systems Design, Inc."s},
			{0x134D, L"VT-Control"s},
			{0x1370, L"Ingenieurbuero Stahlkopf"s},
			{0x13AE, L"Smartpark Creative Solutions"s},
			{0x1460, L"SEIKO Epson Corporation"s},
			{0x1464, L"HUMAL Elektroonika OU"s},
			{0x1490, L"Grid Show Systems Inc."s},
			{0x14A0, L"Intense Lighting, LLC"s},
			{0x14AC, L"Zaklad Elektroniczny AGAT s.c."s},
			{0x1501, L"Artixium France SAS"s},
			{0x1506, L"v2 Lighting Group, Inc."s},
			{0x1507, L"LC Handels GmbH"s},
			{0x1508, L"TommyDMX"s},
			{0x150C, L"ACASS SYSTEMS LLC"s},
			{0x152A, L"SHOWTACLE Ltd."s},
			{0x154E, L"Fire & Magic"s},
			{0x15A0, L"GuangZhou MCSWE Technologies, INC"s},
			{0x15A2, L"FEIMEX"s},
			{0x15D0, L"Music & Lights S.r.l."s},
			{0x161A, L"techKnow Design Ltd."s},
			{0x1626, L"LEDsistem Teknolojileri Tic. Ltd. Sti."s},
			{0x1627, L"Dynamic Visual Solutions LLC"s},
			{0x162A, L"Nerd's Meter"s},
			{0x1690, L"awaptec GmbH"s},
			{0x16A0, L"Audio Effetti Srl"s},
			{0x16AE, L"Electrone Americas Ltd. Co."s},
			{0x16DC, L"Traxon Technologies Ltd."s},
			{0x16E4, L"Aboutshow Color Light Co., LTD"s},
			{0x1701, L"ARTBOX"s},
			{0x170E, L"Serva Transport Systems GmbH"s},
			{0x170F, L"Kezun Stage Lighting Equipment Co., Ltd."s},
			{0x174E, L"Nordgas SNe-lightingsystem"s},
			{0x1750, L"Yuesheng International Limited"s},
			{0x1808, L"Guangzhou Jinye Electronic Technology Co., Ltd."s},
			{0x1809, L"Rotolight"s},
			{0x180A, L"Guangdong Longjoin Optoelectronics Technology Co. Ltd."s},
			{0x180B, L"Light stream"s},
			{0x1871, L"Smoke Factory GmbH"s},
			{0x1872, L"Super-Can Industry Growing Co. Ltd."s},
			{0x1873, L"Zhongshan Wellmake Electronic Technology Co., Ltd."s},
			{0x1888, L"GUANZHOU KAVON STAGE EQUIPMENT CO., LTD."s},
			{0x18A6, L"Steadfast Technology"s},
			{0x1900, L"ADJ Products LLC"s},
			{0x1901, L"Zhongshan Hiline Electronics Co., Ltd."s},
			{0x1938, L"Solid State Luminaires"s},
			{0x1998, L"PLS Electronics Ltd."s},
			{0x19B9, L"Duralamp S.p.A."s},
			{0x19BA, L"Guangzhou Xinzhijie Photoelectric Co., Ltd."s},
			{0x19BB, L"Panalux Ltd."s},
			{0x19BC, L"Newtone AS"s},
			{0x19F8, L"CEZOS Spolka z ograniczona odpowiedzialnoscia, sp.k."s},
			{0x1A00, L"LIGEO GmbH"s},
			{0x1A0D, L"Cineo Lighting"s},
			{0x1A16, L"WADAK GmbH"s},
			{0x1A1A, L"ValDim Waterfountains Ltd."s},
			{0x1A3D, L"Red Lighting s.r.l."s},
			{0x1AFA, L"TMB"s},
			{0x1BB1, L"PH Lightning AB"s},
			{0x1BC0, L"ALS Stanislaw Binkiewicz"s},
			{0x1BC6, L"Studio S Music City"s},
			{0x1C80, L"Vehtec Tecnologia Ltda"s},
			{0x1CAB, L"LTT sp. z o.o."s},
			{0x1E42, L"SSE GmbH"s},
			{0x1E8D, L"Moda Light"s},
			{0x1ECF, L"Masiero s.r.l."s},
			{0x1ED8, L"Antari Lighting And Effects Ltd."s},
			{0x2009, L"Zboxes Intelligent Technology (Shanghai) Co., Ltd."s},
			{0x200A, L"Vault189 Pty. Ltd."s},
			{0x2011, L"Gantom Lighting & Controls"s},
			{0x207F, L"Padura Elektronik GmbH"s},
			{0x20A6, L"ALADIN Architekturlicht GmbH"s},
			{0x20AB, L"IlluminaPi SAS"s},
			{0x20AD, L"AZ e-lite Pte Ltd"s},
			{0x20B6, L"Alkalite LED Technology Corp"s},
			{0x20B8, L"Electron SA"s},
			{0x20B9, L"ARRI -- Arnold & Richter Cine Technik GmbH & Co. Betriebs KG"s},
			{0x20BA, L"AusChristmasLighting"s},
			{0x20BB, L"Able Laser Tech Co., Ltd."s},
			{0x20BC, L"Beijing Pargolite Technology Co., Ltd."s},
			{0x20BD, L"Foshan Yoline Lighting Equipment Co., Ltd."s},
			{0x20BE, L"Uranus Lighting Co., Ltd."s},
			{0x20BF, L"Guangzhou Taifeng Stage Lighting Audio Equipment Factory"s},
			{0x20C0, L"KappaStyle Productions."s},
			{0x20C1, L"BrightBeats, LLC"s},
			{0x20C2, L"Demilight"s},
			{0x20C3, L"PIXILAB Technologies AB"s},
			{0x2121, L"Brother,Brother & Sons Aps"s},
			{0x2122, L"BEGLEC NV"s},
			{0x2130, L"Bart van Stiphout Electronics & Software"s},
			{0x21A1, L"Culture Crew bvba"s},
			{0x21A4, L"CHAUVET Lighting"s},
			{0x21A9, L"CaptSystemes"s},
			{0x21B3, L"Coolon Pty Ltd"s},
			{0x21B4, L"CHROMLECH"s},
			{0x21B5, L"ChromaCove LLC"s},
			{0x2208, L"C.I.M.E.S. (Conception Installation Maintenance En Eclairage & Sonorisation)"s},
			{0x2216, L"D-Light Designs, LLC"s},
			{0x2222, L"D.E.F. Srl"s},
			{0x2224, L"DAS Integrator Pte Ltd"s},
			{0x2239, L"Dream Solutions Ltd."s},
			{0x22A0, L"EAS SYSTEMS"s},
			{0x22A6, L"Elation Lighting Inc."s},
			{0x22A9, L"Engineering Solutions Inc."s},
			{0x22AA, L"EUTRAC - Intelligent Lighting GmbH"s},
			{0x22AB, L"EVC"s},
			{0x22B9, L"Etherlight"s},
			{0x2337, L"Focon Showtechnic"s},
			{0x2338, L"Humanlitech Co., Ltd."s},
			{0x2339, L"Sky-Skan Europe GmbH"s},
			{0x233A, L"4 Frames Lost UG"s},
			{0x23B2, L"Gekko Technology Ltd."s},
			{0x2421, L"HB-Laserkomponenten GmbH"s},
			{0x242A, L"Hungaroflash"s},
			{0x2432, L"Helvar Ltd"s},
			{0x2470, L"Hale Microsystems LLC"s},
			{0x24A3, L"Lighting Innovation Group AG"s},
			{0x24AA, L"IT Ihme"s},
			{0x2500, L"RATOC Systems, Inc."s},
			{0x2501, L"Xero Manufacturing Pty Limited"s},
			{0x2621, L"LEADER LIGHT s.r.o."s},
			{0x2622, L"LDDE Vertriebs Gmbh"s},
			{0x2623, L"Leonh Hardware Enterprise Inc."s},
			{0x2624, L"Lisys Fenyrendszer Zrt."s},
			{0x2626, L"LLT Lichttechnik GmbH&CO.KG"s},
			{0x2627, L"Guangzhou Megota Technology Co., Ltd."s},
			{0x2630, L"Laservision"s},
			{0x2632, L"Lehigh Electric Products"s},
			{0x2635, L"LjusDesign AB"s},
			{0x2636, L"Lumonic Limited"s},
			{0x2637, L"Loxone Electronics GmbH"s},
			{0x263A, L"Lumenec Pty. Ltd."s},
			{0x263C, L"I-Pix Digital Light Ltd."s},
			{0x26A2, L"MEGATECHNICS Ltd."s},
			{0x26B4, L"Milford Instruments Ltd."s},
			{0x2724, L"Nila Inc."s},
			{0x2727, L"Lumikit"s},
			{0x2734, L"Nixer Ltd."s},
			{0x27A8, L"Callegenix LLC"s},
			{0x2821, L"Pioneer Corporation"s},
			{0x2826, L"Peter Maes Technology"s},
			{0x2827, L"Peternet Electronics BVBA"s},
			{0x2829, L"PR-Electronic"s},
			{0x2836, L"Planungsbuero"s},
			{0x28E1, L"MTC maintronic GmbH"s},
			{0x2927, L"ROAL Electronics SpA"s},
			{0x297E, L"Lifetime Music Academy"s},
			{0x2984, L"Getlux Ltd."s},
			{0x2999, L"ALL-DO INTERNATIONAL CO., LTD."s},
			{0x29A1, L"Sturdy Corporation"s},
			{0x29A9, L"SRS Light Design"s},
			{0x29AA, L"Steinigke Showtechnic GmbH"s},
			{0x29B2, L"Selectron Bvba"s},
			{0x29B4, L"Showtec (Highlite International B.V.)"s},
			{0x29B7, L"Sundrax, LLC"s},
			{0x29B8, L"Spotlight s.r.l."s},
			{0x29BA, L"State Automation Pty Ltd."s},
			{0x29E8, L"Stroytsirk LLC"s},
			{0x2A25, L"Thorn Lighting Limited"s},
			{0x2A26, L"Toni Maroni Gmb"s},
			{0x2AAB, L"Urban Visuals & Effects Ltd."s},
			{0x2B28, L"Visual Productions"s},
			{0x2B29, L"MaNima Technologies BV"s},
			{0x2BA2, L"WERPAX bvba"s},
			{0x2BA9, L"The White Rabbit Company, Inc."s},
			{0x2BB4, L"Williams Electronic Design Ltd."s},
			{0x2C1A, L"DMX4ALL GmbH"s},
			{0x2C2A, L"XTBA"s},
			{0x2CE0, L"Lighting Services Inc."s},
			{0x2DC8, L"Stellascapes"s},
			{0x2DDD, L"Waylight"s},
			{0x2DDE, L"Luminlite Electronics Co., Ltd."s},
			{0x2DDF, L"Carpetlight GmbH"s},
			{0x3000, L"PushingPixels"s},
			{0x3001, L"Elemental LED, Inc."s},
			{0x3002, L"Siberian Lighting"s},
			{0x3003, L"ChamSix"s},
			{0x3235, L"de koster Special Effects"s},
			{0x3331, L"DMG Lumiere"s},
			{0x3332, L"Teclumen s.r.l."s},
			{0x3333, L"NightStarry Electronics Co., LTD."s},
			{0x3388, L"Macostar International Ltd."s},
			{0x3434, L"Global Design Solutions, Ltd."s},
			{0x3533, L"Figure 53, LLC"s},
			{0x3534, L"Five4, LLC"s},
			{0x3535, L"Changsha Spark Technology Electronics Ltd."s},
			{0x3536, L"Cindy Professional Lighting Co., Ltd."s},
			{0x3537, L"Novacorp Inc."s},
			{0x3538, L"Lightnet sp. z o. o."s},
			{0x361D, L"Lumishore Ltd. UK"s},
			{0x3638, L"Lumenpulse Lighting Inc."s},
			{0x37D0, L"Boogy Brothers Showequipment"s},
			{0x37D7, L"Lichttechnik & Sonderbau"s},
			{0x37DD, L"Sehr gute GmbH"s},
			{0x3800, L"OndeLight LTD"s},
			{0x3801, L"SFX Controllers Sweden AB"s},
			{0x3805, L"Yifeng Lighting Co., Ltd."s},
			{0x3806, L"ACME EFFECTS LTD."s},
			{0x3868, L"LanBolight Technology Co., LTD."s},
			{0x3888, L"Fly Dragon Lighting Equipment Co.,ltd"s},
			{0x388A, L"Guangzhou Yajiang (Yagang - Silver Star) Photoelectric Equipment Ltd."s},
			{0x3A37, L"TheOlymp - Networking & InterNet Services"s},
			{0x3AFC, L"Black Tank Engineering"s},
			{0x3B10, L"NXP Semiconductors B.V."s},
			{0x3B88, L"Shenzhen Eastar Electronic Co., Ltd."s},
			{0x3D30, L"zactrack Lighting Technologies Gmbh"s},
			{0x400D, L"Quasar Science LLC"s},
			{0x4051, L"SAN JACK ANALOG HOUSE CO., LTD."s},
			{0x4131, L"Altman Stage Lighting"s},
			{0x4141, L"AVAB America, Inc."s},
			{0x4142, L"Filmgear, Inc."s},
			{0x4143, L"AC Lasers"s},
			{0x4144, L"ADB - TTV Technologies nv"s},
			{0x4145, L"ADE ELETTRONICA srl"s},
			{0x4146, L"AUS FX"s},
			{0x4149, L"Anidea Engineering, Inc."s},
			{0x414C, L"Artistic Licence Engineering Ltd."s},
			{0x414D, L"Amptown Lichttechnik GmbH"s},
			{0x414E, L"Anytronics Ltd."s},
			{0x4150, L"Apogee Lighting"s},
			{0x4151, L"Aquarii, Inc."s},
			{0x4153, L"Audio Scene"s},
			{0x4154, L"Arnold Tang Productions"s},
			{0x4156, L"Audio Visual Devices P/L"s},
			{0x4164, L"Adelto Industries Ltd."s},
			{0x416C, L"Alenco BV"s},
			{0x4172, L"ARNOLD LICHTTECHNIK"s},
			{0x4173, L"Astera LED Technology GmbH"s},
			{0x4179, L"AYRTON"s},
			{0x4241, L"BECKHOFF Automation GmbH"s},
			{0x4243, L"Bill Coghill Company : Bill Coghill Design"s},
			{0x4245, L"Bytecraft Entertainment Pty Ltd"s},
			{0x424F, L"BOTEX"s},
			{0x4253, L"Barco"s},
			{0x42A2, L"Birket Engineering, Inc."s},
			{0x4321, L"Design Partners of Canada"s},
			{0x4344, L"CDCA Ltd."s},
			{0x4347, L"CAST Software"s},
			{0x4349, L"C.I.Tronics Lighting Designers Ltda"s},
			{0x434B, L"Color Kinetics Inc."s},
			{0x434C, L"Crealux GmbH & Co. KG"s},
			{0x434D, L"Coemar Spa"s},
			{0x434F, L"Cortex Design"s},
			{0x4350, L"CLAY PAKY S.p.A"s},
			{0x4353, L"Capricorn Software"s},
			{0x4354, L"City Theatrical, Inc."s},
			{0x4358, L"Connex GmbH"s},
			{0x4369, L"Cinetix Medien u. Interface GmbH"s},
			{0x436F, L"CODEM MUSIC S.r.l."s},
			{0x4441, L"DIGITAL ART SYSTEM"s},
			{0x4442, L"ELETTROLAB S.r.l."s},
			{0x4443, L"Claudio Dal Cero Engineering"s},
			{0x4444, L"D.O.M.  Datenverarbeitung GmbH"s},
			{0x4445, L"Dezelectric Kft."s},
			{0x4446, L"Doug Fleenor Design, Inc."s},
			{0x4449, L"Durand Interstellar, Inc."s},
			{0x444C, L"Dove Lighting Systems, Inc."s},
			{0x444D, L"Digimedia Multimedia Lighting Solutions"s},
			{0x444E, L"DALCNET SRL"s},
			{0x4450, L"DMXPROFI.EU GmbH i.G."s},
			{0x4453, L"Guangzhou Desheng Lighting Industrial Co., Ltd."s},
			{0x4456, L"Devantech Ltd."s},
			{0x4466, L"DF elettronica s.r.l."s},
			{0x4469, L"Diamante Lighting Srl"s},
			{0x446C, L"Guangdong Delos Lighting Industrial Co.,Ltd."s},
			{0x4533, L"LEDdynamics, Inc."s},
			{0x453A, L"E:cue  Control GmbH"s},
			{0x4541, L"Engineering Arts"s},
			{0x4543, L"EC Elettronica Srl"s},
			{0x4544, L"Electronics Diversified LLC"s},
			{0x4545, L"EastSun Technology Co. Ltd."s},
			{0x454C, L"Ingenieurbuero fuer Nachrichtentechnik in der Studio und Veranstaltungstechnik"s},
			{0x454D, L"ELM Video Technology, Inc."s},
			{0x454E, L"ENTTEC Pty Ltd"s},
			{0x4552, L"EREA"s},
			{0x4553, L"ERAL srl"s},
			{0x4554, L"Entertainment Technology"s},
			{0x4563, L"Les Eclairages Lou Inc."s},
			{0x456C, L"Element Labs Inc."s},
			{0x4631, L"OKEROAB AB"s},
			{0x464C, L"Flashlight/Ampco Holding"s},
			{0x4653, L"IT & Eventtechnik Fabian Stumpf"s},
			{0x4656, L"Flexvisual"s},
			{0x4657, L"The Fountain Workshop Ltd."s},
			{0x4658, L"MAGIC FX B.V."s},
			{0x4678, L"Global Special Effects"s},
			{0x4744, L"Goddard Design Co."s},
			{0x4745, L"GPE srl"s},
			{0x4747, L"G&G LED Lighting"s},
			{0x474C, L"G-LEC Europe GmbH"s},
			{0x4750, L"DES"s},
			{0x4752, L"Greenlite"s},
			{0x4753, L"Guangzhou Haoyang Electronic Co., Ltd."s},
			{0x476C, L"General Luminaire (Shanghai) Ltd."s},
			{0x4800, L"VOD VISUAL.CO. (UK) Ltd."s},
			{0x4801, L"Capture Visualisation AB"s},
			{0x4843, L"Horizon Control Inc."s},
			{0x4844, L"HxDx"s},
			{0x4845, L"Howard Eaton Lighting Ltd."s},
			{0x484C, L"HBE Lighting Systems"s},
			{0x484F, L"Hollywood Controls Inc."s},
			{0x4856, L"Enfis Ltd"s},
			{0x4881, L"Rena Electronica B.V."s},
			{0x4941, L"inoage GmbH"s},
			{0x4942, L"IBEX UK Limited"s},
			{0x4944, L"Ingham Designs"s},
			{0x4945, L"Insta Elektro GmbH"s},
			{0x4947, L"IGuzzini illuminazione spa"s},
			{0x4948, L"Ice House Productions"s},
			{0x494C, L"I-Lum"s},
			{0x494E, L"Interactive Technologies, Inc."s},
			{0x4950, L"Interesting Products, Inc."s},
			{0x4951, L"IQAir AG"s},
			{0x4952, L"Invisible Rival Incorporated"s},
			{0x4953, L"Integrated System Technologies Ltd."s},
			{0x4954, L"Integrated Theatre, Inc."s},
			{0x4973, L"Innovation Solutions Ltd."s},
			{0x4A31, L"Joshua 1 Systems Inc."s},
			{0x4A41, L"JANUS srl"s},
			{0x4A42, L"JB-lighting GmbH"s},
			{0x4A48, L"James Harris"s},
			{0x4A4C, L"Johnsson Lighting Technologies AB"s},
			{0x4A53, L"JSC 'MFG'"s},
			{0x4A54, L"James Thomas Engineering"s},
			{0x4A61, L"Jands Pty Ltd."s},
			{0x4ACC, L"RVL techniek"s},
			{0x4B00, L"Gabor Galyas Lighting"s},
			{0x4B42, L"KissBox"s},
			{0x4B43, L"TmTech Electronic Co.,Ltd."s},
			{0x4B46, L"Kino Flo, Inc."s},
			{0x4B4C, L"KLH Electronics PLC"s},
			{0x4B4D, L"KMX Inc."s},
			{0x4B55, L"kuwatec, Inc."s},
			{0x4C20, L"LAM32 srl"s},
			{0x4C41, L"LaserAnimation Sollinger GmbH"s},
			{0x4C44, L"LVDIAN PHOTOELECTRIC SCIENCE TECHNOLOGY LIMITED"s},
			{0x4C45, L"Leviton Manufacturing Co., Inc."s},
			{0x4C47, L"LightGeist Ltd."s},
			{0x4C4C, L"LUMINEX Lighting Control Equipment bvba"s},
			{0x4C4D, L"Ultratec Special Effects"s},
			{0x4C50, L"LightProcessor Ltd"s},
			{0x4C52, L"High End Systems Inc."s},
			{0x4C53, L"Licht-, Steuer- und Schaltanlagenbau GmbH (LSS GmbH)"s},
			{0x4C54, L"Licht-Technik"s},
			{0x4C55, L"LumenRadio AB"s},
			{0x4C56, L"LEDValley Technologies Sdn Bhd"s},
			{0x4C57, L"LightWild LC"s},
			{0x4C58, L"Lex Products Corp."s},
			{0x4C59, L"Laser Technology Ltd."s},
			{0x4C5A, L"LightMinded Industries, Inc."s},
			{0x4C5A, L"Sumolight GmbH"s},
			{0x4C5B, L"LightLife, Gesellschaft fur audiovisuelle Erlebnisse mbH"s},
			{0x4C64, L"LED Team"s},
			{0x4C65, L"Legargeant and Associates"s},
			{0x4C69, L"LIGHTOLIER"s},
			{0x4C6C, L"Lampo Lighting Designers"s},
			{0x4C73, L"LSC Lighting Systems (Aust) Pty. Ltd."s},
			{0x4CDC, L"acdc LED Ltd."s},
			{0x4CE5, L"LED Company s.r.o."s},
			{0x4D41, L"MA Lighting Technology GmbH"s},
			{0x4D42, L"LAN Systems--Midibox project"s},
			{0x4D44, L"Les Generateurs de brouillard MDG Fog Generators Ltd."s},
			{0x4D4C, L"Mode Lighting (UK) Ltd."s},
			{0x4D50, L"Martin Professional A/S"s},
			{0x4D54, L"medien technik cords"s},
			{0x4D56, L"Avolites Ltd."s},
			{0x4D58, L"MX design"s},
			{0x4D5A, L"Covert Science GmbH"s},
			{0x4D61, L"MARTINI S.p.A."s},
			{0x4D77, L"Mueller Elektronik"s},
			{0x4E41, L"Company NA"s},
			{0x4E4A, L"NJD Electronics"s},
			{0x4E4C, L"NOVALIGHT S.r.l."s},
			{0x4E57, L"AIM Northwest"s},
			{0x4E69, L"Niko"s},
			{0x4F41, L"Oase GmbH"s},
			{0x4F43, L"Offstage Controls (formerly Obsidian Control)"s},
			{0x4F4C, L"DDS Elettronica"s},
			{0x4F75, L"Outsight Pty Ltd."s},
			{0x5000, L"http://www.orangepi-dmx.org"s},
			{0x5001, L"Hua Yuan Ke Tai"s},
			{0x5002, L"Shanghai Shylon Optoelectronic Technology Co., Ltd."s},
			{0x5003, L"Futlight Optoelectronics Co.,Ltd."s},
			{0x5004, L"Shanghai Sansi Electronic Engineering Co.,Ltd"s},
			{0x5005, L"MEDIAM Ltd. (Modus brand)"s},
			{0x5006, L"ENEDO Power SpA"s},
			{0x5007, L"Alfalite"s},
			{0x5008, L"Chengdu Chengyu Electronic Technology Co., Ltd."s},
			{0x5009, L"Izzro Optoelectronics Technology Co., Ltd."s},
			{0x500A, L"AU Optronics Corporation (AUO)"s},
			{0x500B, L"WebKat Eletronic's"s},
			{0x500C, L"L.E.C. Societe Lyonnaise D' Equipement Et De Controle"s},
			{0x5010, L"Shenzhen Viye Technology Co., Ltd."s},
			{0x5011, L"Guangzhou Skydance Co., Ltd."s},
			{0x5017, L"American Lighting"s},
			{0x5040, L"Guangzhou Color Imagination LED Lighting Ltd."s},
			{0x5041, L"Philips Entertainment Lighting Asia"s},
			{0x5043, L"Pathway Connectivity Inc."s},
			{0x504C, L"Peperoni Lighting-Solutions"s},
			{0x504D, L"Peter Meyer Project Management Adviser GmbH"s},
			{0x504E, L"Uni-Bright nv"s},
			{0x5050, L"Newton Engineering and Design Group LLC"s},
			{0x5051, L"PDQ Manufacturing, Inc"s},
			{0x5052, L"Production Resource Group"s},
			{0x5053, L"Philips Selecon"s},
			{0x5058, L"PXM s.c."s},
			{0x5062, L"LED, Inc."s},
			{0x5065, L"Peradise"s},
			{0x5066, L"Pfannenberg GmbH"s},
			{0x5068, L"Philips Lighting BV"s},
			{0x5070, L"Show Light Oy"s},
			{0x5071, L"Raindrop-Media"s},
			{0x5072, L"ARRI Rental Deutschland GmbH"s},
			{0x5075, L"Pulsar Light of Cambridge Ltd."s},
			{0x5099, L"Altec Di Gregorio Andrea"s},
			{0x5100, L"Luxibel"s},
			{0x5101, L"LBT Electronics Pvt. Ltd."s},
			{0x5102, L"INDATA d.o.o."s},
			{0x512D, L"DJPOWER ELECTRONIC STAGE LIGHTING FIXTURE FACTORY (GUANGZHOU)"s},
			{0x5149, L"JAP Optoelectronic Ltd."s},
			{0x514D, L"QMAXZ lighting"s},
			{0x5153, L"QuickSilver Controls, Inc."s},
			{0x5168, L"Shenzhen Sunricher Technology Co.,Ltd."s},
			{0x516C, L"Quicklights"s},
			{0x51D7, L"Innovative Dimmers LLC (Ratpac dimmers)"s},
			{0x51D8, L"Amperor Electronics (Shenzhen) Co., Ltd."s},
			{0x5200, L"Shenzhen Aotian Technology Co. , Ltd."s},
			{0x5201, L"Crestron Electronics, Inc."s},
			{0x5202, L"Shenzhen Lianjin Photoelectricity Co., Ltd."s},
			{0x5244, L"Revolution Display"s},
			{0x524C, L"Radical Lighting Ltd."s},
			{0x524D, L"RUIZ TECH"s},
			{0x524E, L"RNC Systems Inc."s},
			{0x5250, L"RootPath Ltd."s},
			{0x5252, L"RoscoLab Ltd."s},
			{0x5253, L"Robe Show Lighting s.r.o."s},
			{0x5341, L"Stage Technologies Limited"s},
			{0x5342, L"Industrias Sola Basic S.A. de C.V."s},
			{0x5343, L"Ocean Thin Films Inc."s},
			{0x5344, L"Stardraw.com Ltd."s},
			{0x5345, L"Selador"s},
			{0x5346, L"Synthe FX, LLC"s},
			{0x5347, L"SGM Technology For Lighting SPA"s},
			{0x5348, L"Schreder"s},
			{0x5349, L"Soundsculpture Incorporated"s},
			{0x534A, L"SAS Productions"s},
			{0x534B, L"SK-Software"s},
			{0x534C, L"SOUNDLIGHT"s},
			{0x534E, L"Sand Network Systems"s},
			{0x5353, L"Sean Sill"s},
			{0x5354, L"Stagetronics Ltda"s},
			{0x5355, L"Lochmun Ltd."s},
			{0x5356, L"OOO SAMLIGHT"s},
			{0x5363, L"SpaceCannon vH"s},
			{0x5368, L"ShowCAD Control Systems Ltd."s},
			{0x536C, L"StageLine Electronic"s},
			{0x5370, L"Chroma-Q"s},
			{0x5374, L"STG-Beikirch Industrieelektronik + Sicherheitstechnik GmbH & Co. KG"s},
			{0x5376, L"SV-wtu eU"s},
			{0x5377, L"SWISSON AG"s},
			{0x5379, L"Singularity (UK) Ltd."s},
			{0x53A8, L"Simon Tech"s},
			{0x5431, L"AUTOLUX Handels- und ProduktionsgmbH"s},
			{0x5441, L"TecArt Lighting"s},
			{0x5444, L"Technographic Displays Ltd."s},
			{0x5445, L"TESI Elettronica srl"s},
			{0x544C, L"Tempest Lighting Inc."s},
			{0x5453, L"TalentStorm Enterprises, Inc."s},
			{0x5454, L"TamaTech Labo Company Ltd,"s},
			{0x5459, L"TDE-Lighttech B.V."s},
			{0x5550, L"UP-LUX Eletronica Ltda."s},
			{0x5555, L"Martin Sukale Medientechnik GbR"s},
			{0x55AA, L"Emilum GmbH"s},
			{0x564C, L"Vari-Lite, Inc."s},
			{0x5651, L"Vision Quest Lighting Inc."s},
			{0x5652, L"Megapixel Visual Reality"s},
			{0x5653, L"Viso Systems Aps"s},
			{0x5655, L"Shenzhen CAS VU Technologies Co., Ltd."s},
			{0x5744, L"W-DEV"s},
			{0x5746, L"Wildfire, Inc."s},
			{0x5747, L"Wenger / JR Clancy"s},
			{0x5753, L"Wireless Solution Sweden AB"s},
			{0x5754, L"LIGHTMAN (Interlite AB)"s},
			{0x5759, L"Wybron, Inc."s},
			{0x584C, L"X-Laser"s},
			{0x584D, L"Xtraordinary Musical Accolade Systems"s},
			{0x5858, L"Illuminance Technologies"s},
			{0x5865, L"XENON ARCHITECTURAL LIGHTING"s},
			{0x586C, L"Eurolumen (Shanghai) Lighting Co., LTD"s},
			{0x586D, L"www.doityourselfchristmas.com hobbyists"s},
			{0x5888, L"Plsao Optoelectronics Technology Co., Ltd."s},
			{0x5A53, L"Zingerli Show Engineering"s},
			{0x5C40, L"OXO"s},
			{0x5D00, L"L1 Inc."s},
			{0x5D01, L"MTS Medientechnik GmbH"s},
			{0x5D02, L"Underwater Lights Limited"s},
			{0x5DAC, L"Mediatec Group"s},
			{0x5E5D, L"Multisenses GmbH"s},
			{0x5E5E, L"Converging Systems Inc."s},
			{0x6019, L"Artifice Industries Ltd."s},
			{0x6100, L"Krobox Sdn Bhd"s},
			{0x610A, L"Visenge Pty. Ltd"s},
			{0x6123, L"CMYLight (S) Pte. Ltd."s},
			{0x6124, L"Fiilex"s},
			{0x614C, L"Alektra AB"s},
			{0x6154, L"Advatek Lighting"s},
			{0x6164, L"AVID Labs"s},
			{0x616C, L"Advanced Lighting Systems"s},
			{0x6200, L"LUCITAG Ltd."s},
			{0x6201, L"NuDelta Digital, LLC"s},
			{0x6202, L"ESCO Sp. z o.o."s},
			{0x6203, L"Flektor"s},
			{0x6204, L"Shenzhen Absen Optoelectronic Co., Ltd"s},
			{0x6205, L"Zhuhai Ltech Technology Co., Ltd."s},
			{0x6206, L"Lighting Innovation Company, LLC"s},
			{0x6273, L"B&S Elektronische Geräte GmbH"s},
			{0x6342, L"Mega Systems Inc."s},
			{0x6364, L"CDS advanced technology bv"s},
			{0x636D, L"Cambridge Micro Engineering Limited"s},
			{0x641A, L"Heliospectra AB"s},
			{0x644C, L"bdL KG"s},
			{0x6461, L"Digilin Australia"s},
			{0x6464, L"Dangeross Design"s},
			{0x646C, L"dilitronics GmbH"s},
			{0x646F, L"eldoLED BV"s},
			{0x6472, L"Ingenieurburo Steffens"s},
			{0x64B9, L"Finelite, Inc."s},
			{0x6542, L"eBrain GmbH"s},
			{0x6543, L"LES-TV Ltd."s},
			{0x6547, L"euroGenie"s},
			{0x6553, L"EtherShow"s},
			{0x6555, L"Shantea Controls"s},
			{0x6565, L"Stratus Systems LLC"s},
			{0x656C, L"ELC lighting"s},
			{0x6573, L"Environmental Lighting Solutions"s},
			{0x6574, L"Electronic Theatre Controls, Inc."s},
			{0x6576, L"eventa Aktiengesellschaft"s},
			{0x6600, L"WANTS Electronics Co. Ltd."s},
			{0x6644, L"Sunlab Technologies S.L."s},
			{0x666D, L"MAD-Effects"s},
			{0x6673, L"Freescale Semiconductor U.K. Ltd."s},
			{0x6756, L"Lumisia Co., Ltd."s},
			{0x676C, L"GLP German Light Products GmbH"s},
			{0x67F0, L"Toshiba Lighting & Technology Corporation"s},
			{0x6816, L"ChamberPlus Co., Ltd"s},
			{0x6864, L"James Embedded Systems Engineering (JESE Ltd)"s},
			{0x6865, L"Hubbell Entertainment, Inc."s},
			{0x686C, L"HERA LED"s},
			{0x694C, L"iLight Technologies Inc"s},
			{0x6969, L"Better Way Lighting"s},
			{0x6974, L"Ittermann electronic GmbH"s},
			{0x6A6A, L"Roxx GmbH"s},
			{0x6A6B, L"JPK Systems Limited"s},
			{0x6B64, L"Key Delfin"s},
			{0x6B69, L"Magical Fountain SA de CV (Magic Fountain)"s},
			{0x6BEA, L"Remoticom BV"s},
			{0x6BED, L"Planar Systems, Inc."s},
			{0x6BEE, L"Ephesus Lighting"s},
			{0x6BEF, L"Shenzhen Ifountain Technology Ltd."s},
			{0x6C6D, L"Zumtobel Lighting GmbH"s},
			{0x6C78, L"Claude Heintz Design"s},
			{0x6C92, L"Ambra Elettronica s.r.l."s},
			{0x6D61, L"MAL Effekt-Technik GmbH"s},
			{0x6D62, L"MBN GmbH"s},
			{0x6D63, L"Sein & Schein GmbH"s},
			{0x6E00, L"LEDeco solution, s.r.o."s},
			{0x6F00, L"Guangzhou Huaying Stage Lighting Equipment Co. Ltd."s},
			{0x6F01, L"DAVAI!JPL"s},
			{0x6F02, L"hazebase (Uta Raabe e.K.)"s},
			{0x6FEA, L"Lumina Visual Productions"s},
			{0x6FEB, L"Insight Lighting"s},
			{0x6FEC, L"Arc Lighting Co. Ltd."s},
			{0x6FED, L"Explorentis"s},
			{0x6FEE, L"fos design sp. z o.o."s},
			{0x7000, L"Nippon Ceramic Co., Ltd."s},
			{0x700A, L"Guangzhou Leemc Lighting Tech., Co., Ltd."s},
			{0x700B, L"Vice Lighting DWC LLC"s},
			{0x7068, L"Pharos Architectural Controls"s},
			{0x7070, L"SBT GmbH"s},
			{0x7072, L"Pr-Lighting Ltd."s},
			{0x7078, L"PixelRange Inc."s},
			{0x70F0, L"Pangolin Laser Systems, Inc."s},
			{0x7151, L"The Light Source, Inc."s},
			{0x7363, L"Sean Christopher FX"s},
			{0x7365, L"Ballantyne Strong Inc."s},
			{0x736C, L"Strand Lighting Ltd."s},
			{0x7400, L"Danalux"s},
			{0x7401, L"Harvatek Corporation"s},
			{0x7402, L"Chris Kallas"s},
			{0x7403, L"Yenrich Technology Corporation"s},
			{0x7764, L"WET"s},
			{0x7765, L"MKT engineering GmbH & Co. KG"s},
			{0x7777, L"DVT Light"s},
			{0x7788, L"DigitaLicht AG"s},
			{0x780E, L"Mole-Richardson Co."s},
			{0x783A, L"Audiolux Devices LLC"s},
			{0x786C, L"XLN-t bvba"s},
			{0x7888, L"Tontron Photoelectric Co., Limited"s},
			{0x78B4, L"LED Flex Limited"s},
			{0x7900, L"Leprecon / CAE, Inc."s},
			{0x79BC, L"DC Reactive"s},
			{0x7A70, L"Open Lighting"s},
			{0x7AA0, L"Anaren Inc."s},
			{0x7AAA, L"WEAD (Wagner Electronic and Design)"s},
			{0x7AAB, L"Hyundai Fomex Co., Ltd."s},
			{0x7B1B, L"DimLight Ltd."s},
			{0x7D00, L"expanseElectronics"s},
			{0x7D61, L"HMB|TEC GmbH"s},
			{0x7DE7, L"Guangzhou ILightings Equipment Co., Ltd."s},
			{0x7DE8, L"Shenzhen LAMP Technology Co., Ltd."s},
			{0x7DEA, L"RobLight A/S"s},
			{0x7DEB, L"Krypton"s},
			{0x7DEE, L"zencontrol Pty Ltd"s},
			{0x7EE7, L"Arthur Digital Solutions Kft"s},
			{0x7EE8, L"Guangzhou Yingfeng Lighting Equipment Co., Ltd."s},
			{0x7EE9, L"Technology Kitchen"s},
			{0x7EEA, L"Cartwright Engineering"s},
			{0x7EEB, L"mylaserpage"s},
			{0x7EEC, L"SHENZHEN LP Display"s},
			{0x7EED, L"Look Solutions GmbH & Co. KG"s},
			{0x7EEE, L"General Lighting Electronic Co., Ltd."s},
			{0x7EEF, L"Huizhou Mounteck Technology Co., Ltd."s},
			{0x7FF0, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF1, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF2, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF3, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF4, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF5, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF6, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF7, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF8, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FF9, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FFA, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FFB, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FFC, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FFD, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FFE, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0x7FFF, L"RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY"s},
			{0xFFFF, L"ESTA"s},

		}; // std::map
	} // ManufacturerIDs
} // ESTA
#endif // ESTA_MFCTRIDS_HPP
