name: Run scraper scripts weekly and on push
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  
concurrency:
  group: ${{ github.workflow }}
    
jobs:
  CPlusPlus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install BeautifulSoup4
      
      - name: Run scraper script
        run: python scripts/generate_esta_mfctrids_hpp.py
        
      - name: Ignore changes only to the date comment in the header
        shell: bash
        run: git diff -I '\* @date' --quiet --exit-code && git reset --hard || echo Updates to commit
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9 
        with:
          default_author: github_actions
          message: 'Github actions auto update of C++ header'
          add: 'esta_mfcrids.hpp'

  CSV:
    needs: CPlusPlus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install BeautifulSoup4
      
      - name: Run scraper script
        run: python scripts/generate_esta_mfctrids_csv.py
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9 
        with:
          default_author: github_actions
          message: 'Github actions auto update of CSV file'
          add: 'esta_mfcrids.csv'

  JSON:
    needs: CSV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install BeautifulSoup4
      
      - name: Run scraper script
        run: python scripts/generate_esta_mfctrids_json.py

      - name: Ignore changes only to the date
        shell: bash
        run: git diff -I 'lastUpdated' --quiet --exit-code && git reset --hard || echo Updates to commit
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9 
        with:
          default_author: github_actions
          message: 'Github actions auto update of JSON file'
          add: 'esta_mfcrids.json'
